"""Cut the stone dots of the §19.1 sheet into the sandstone detail texture
(src/voxel/sheetDots.ts). Needs Pillow: pip install pillow.

  python3 docs/kit-work/sheet-dots.py [--preview out.png]

Twelve stone faces (four from each of the clean, warm and dark "Tile / texture
(top view)" squares), each 52 sheet pixels cut well inside its rim and shrunk
to 12 x 12 texels (a 0.5 m stone face at 24 texels per metre, about the
sheet's dot size). Each face keeps only its dots: it is divided by its own
blurred self in linear light, mostly as brightness (a little of the dots' own
tint stays), and scaled to one common contrast. So the texture holds ratios
around 1, the block's colour (its palette tone) stays in charge of the hue and
the `grain` of the family sets how strong the dots are.
"""
import base64, os, sys
from PIL import Image, ImageFilter

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SHEET = os.path.join(ROOT, 'assets', 'angkor detail', 'section 19', '85D8F367-EBB2-45B5-94C0-E9ED5A7CE350.PNG')
OUT = os.path.join(ROOT, 'src', 'voxel', 'sheetDots.ts')
N = 12  # texels per stone face
CUT = 52  # sheet pixels per stone face
# Tile squares of the clean, warm and dark cards (their top-left corners).
TILES = [(38, 475), (291, 475), (544, 478)]
# Stone faces inside a tile: the four big stones, clear of their rims.
FACES = [(10, 7), (136, 9), (9, 82), (137, 86)]
LO, HI = 0.4, 1.6  # stored ratio range
TINT = 0.35  # share of each dot's own tint kept (0 = grey dots)
STD = 0.15  # brightness spread of every face (sheet: 0.09 clean tile … 0.19 cube faces)

def lin(v):
    v /= 255
    return v / 12.92 if v <= 0.04045 else ((v + 0.055) / 1.055) ** 2.4

sheet = Image.open(SHEET).convert('RGB')
faces = []
for tx, ty in TILES:
    for fx, fy in FACES:
        x, y = tx + fx, ty + fy
        faces.append(sheet.crop((x, y, x + CUT, y + CUT)).resize((N, N), Image.BOX))
cols = 4
rows = len(faces) // cols
W, H = cols * N, rows * N
data = bytearray(W * H * 3)
preview = Image.new('RGB', (W, H))
for n, face in enumerate(faces):
    px = [[lin(c) for c in face.getpixel((i, j))] for j in range(N) for i in range(N)]
    # Smooth shading of the face (a blur a third of its size) in linear light.
    blur = face.filter(ImageFilter.GaussianBlur(N / 3))
    sm = [[lin(c) for c in blur.getpixel((i, j))] for j in range(N) for i in range(N)]
    ratio = [[p[c] / max(s[c], 1e-4) for c in range(3)] for p, s in zip(px, sm)]
    mean = [sum(r[c] for r in ratio) / len(ratio) for c in range(3)]
    ratio = [[r[c] / mean[c] for c in range(3)] for r in ratio]
    # Mostly brightness: each channel leans to the texel's mean ratio.
    ratio = [[TINT * r[c] + (1 - TINT) * sum(r) / 3 for c in range(3)] for r in ratio]
    lum = [sum(r) / 3 for r in ratio]
    std = (sum((l - 1) ** 2 for l in lum) / len(lum)) ** 0.5
    ratio = [[1 + (r[c] - 1) * STD / std for c in range(3)] for r in ratio]
    mean = [1, 1, 1]
    ox, oy = (n % cols) * N, (n // cols) * N
    for k, r in enumerate(ratio):
        i, j = k % N, k // N
        o = ((oy + j) * W + ox + i) * 3
        for c in range(3):
            v = min(HI, max(LO, r[c] / mean[c]))
            data[o + c] = round((v - LO) / (HI - LO) * 255)
        preview.putpixel((ox + i, oy + j), tuple(min(255, round(r[c] / mean[c] * 160)) for c in range(3)))

with open(OUT, 'w') as f:
    f.write('// Generated by docs/kit-work/sheet-dots.py from the §19.1 sheet — do not edit.\n')
    f.write('/** Sandstone detail: brightness ratios (RGB, stored as lo + (hi − lo) · byte / 255) of twelve stone faces of 12 × 12 texels. */\n')
    f.write(f"export const SHEET_DOTS = {{ width: {W}, height: {H}, texels: {N}, lo: {LO}, hi: {HI}, rgb: '{base64.b64encode(bytes(data)).decode()}' }};\n")
if '--preview' in sys.argv:
    preview.resize((W * 12, H * 12), Image.NEAREST).save(sys.argv[sys.argv.index('--preview') + 1])
print(f'{OUT}: {W} x {H} texels')
