import type { PlaceDef, PlaceText } from '../layout';
import type { Lang } from '../types';

/**
 * The map screen's words in Khmer (first) and English. The ខ្មែរ / EN switch
 * (top right, ui.ts) sets the language; it is kept with the settings
 * (`MapSettings.lang`). Shots: `lang=en|km`.
 *
 * - `t(key, vars)`: a word in the current language; `{x}` in it is filled from `vars.x`.
 * - `placeText(p)`: a place's name, subtitle, blurb and facts (layout.ts `km`).
 * - `num(s)`: Khmer digits in Khmer.
 * - `onLang(fn)`: parts that show words fill them again when it changes.
 *
 * Khmer glyphs come from 'Kantumruy Pro' (text) and 'Koulen' (titles),
 * after the Latin fonts in map.css (the browser picks per letter).
 */
const WORDS = {
  title: { km: 'មរតកអង្គរ', en: 'Angkor Heritage' },
  tagline: { km: 'ជ្រើសរើសដំណើរផ្សងព្រេងបន្ទាប់របស់អ្នក', en: 'Choose your next expedition' },
  loading: { km: 'កំពុងឈូសឆាយផ្លូវកាត់ព្រៃ…', en: 'Clearing the path through the jungle…' },
  // (the loading screen's button once the map is built: its click also turns the sound on)
  loadGo: { km: 'ចាប់ផ្ដើម', en: 'Start' },
  hint: { km: 'រុករកតំបន់ខ្ពង់រាបបុរាណនៃអង្គរ', en: 'Explore the ancient highlands of Angkor' },
  jumpIn: { km: 'លោតចុះ', en: 'Jump in' },
  jumpInAria: { km: 'លោតចុះ៖ ជ្រើសរើសឆ័ត្រយោង ឬខ្លែងហោះ (J)', en: 'Jump in: choose a parachute or a hang glider (J)' },
  jumpChute: { km: 'ឆ័ត្រយោង', en: 'Parachute' },
  jumpChuteNote: { km: 'អណ្ដែតចុះថ្នមៗ', en: 'Float down gently' },
  jumpGlider: { km: 'ខ្លែងហោះ', en: 'Hang glider' },
  jumpGliderNote: { km: 'ហោះហើរពីលើប្រាសាទ', en: 'Soar over the temples' },
  jumpClose: { km: 'បិទ (Esc)', en: 'Close (Esc)' },
  places: { km: 'ទីកន្លែងលើផែនទី', en: 'Places on the map' },
  pinSoon: { km: ' (ឆាប់ៗនេះ)', en: ' (coming soon)' },
  map: { km: 'ផែនទី', en: 'Map' },
  backToMap: { km: 'ត្រឡប់ទៅផែនទីវិញ', en: 'Back to the map' },
  destination: { km: 'គោលដៅ', en: 'Destination' },
  begin: { km: 'ចាប់ផ្ដើមដំណើរ', en: 'Begin expedition' },
  soon: { km: 'ឆាប់ៗនេះ', en: 'Coming soon' },
  soonNote: { km: 'ផ្លូវនេះកំពុងឈូសឆាយនៅឡើយ។', en: 'This path is still being cleared.' },
  settingOut: { km: 'កំពុងចេញដំណើរទៅ {name}', en: 'Setting out for {name}' },
  ready: { km: 'រួចរាល់ហើយ។', en: 'Ready to begin.' },
  soonLive: { km: 'ឆាប់ៗនេះ។', en: 'Coming soon.' },
  backLive: { km: 'ត្រឡប់ទៅផែនទីវិញ។', en: 'Back to the map.' },
  exploring: { km: 'កំពុងរុករកផែនទី។', en: 'Exploring the map.' },
  settings: { km: 'ការកំណត់', en: 'Settings' },
  closeSettings: { km: 'បិទការកំណត់', en: 'Close settings' },
  // (the settings' tabs, ui.ts: the sound tab is `sound`; the tab bar's name for a screen reader)
  settingsTabs: { km: 'ផ្នែកនៃការកំណត់', en: 'Settings sections' },
  tabGeneral: { km: 'ទូទៅ', en: 'General' },
  tabGraphics: { km: 'រូបភាព', en: 'Graphics' },
  tabPlay: { km: 'ការលេង', en: 'Play' },
  tabAbout: { km: 'អំពី', en: 'About' },
  sound: { km: 'សំឡេង', en: 'Sound' },
  master: { km: 'សំឡេងរួម', en: 'Master' },
  masterTip: { km: 'គ្រប់សំឡេង', en: 'All sound' },
  music: { km: 'តន្ត្រី', en: 'Music' },
  musicTip: { km: 'តន្ត្រីស្ងប់ៗ', en: 'The calm music' },
  ambience: { km: 'បរិយាកាស', en: 'Ambience' },
  ambienceTip: { km: 'ខ្យល់ សត្វស្លាប សត្វល្អិត និងកង្កែប', en: 'Wind, birds, insects and frogs' },
  water: { km: 'ទឹក', en: 'Water' },
  waterTip: { km: 'ទឹកធ្លាក់ និងទន្លេ កាន់តែជិតកាន់តែឮខ្លាំង', en: 'Waterfalls and rivers, louder the closer you are' },
  animals: { km: 'សត្វ', en: 'Animals' },
  animalsTip: { km: 'សំឡេងសត្វនៅជិតៗ៖ ដំរី ស្វា មាន់…', en: 'Calls of the animals nearby: elephants, monkeys, the rooster…' },
  steps: { km: 'ជំហាន', en: 'Footsteps' },
  stepsTip: { km: 'ជំហានរបស់អ្នករុករក លើស្មៅ ថ្ម ខ្សាច់ និងទឹក', en: "The explorer's steps on grass, stone, sand and water" },
  moves: { km: 'សកម្មភាព', en: 'Actions' },
  movesTip: { km: 'លោត ចុះចត ឆ័ត្រយោង ខ្លែងហោះ ការចែវទូក និងកាមេរ៉ា', en: 'Jumps and landings, parachute, hang glider, paddle and camera' },
  ui: { km: 'ប៊ូតុង', en: 'Interface' },
  uiTip: { km: 'សំឡេងចុចប៊ូតុង និងបើកបិទផ្ទាំង', en: 'Clicks of the buttons and panels' },
  soundAround: { km: 'ជុំវិញអ្នក', en: 'Around you' },
  soundYours: { km: 'សំឡេងរបស់អ្នក', en: 'Your sounds' },
  percent: { km: '{n} ភាគរយ', en: '{n} percent' },
  time: { km: 'ពេលវេលា', en: 'Time of day' },
  day: { km: 'ថ្ងៃ', en: 'Day' },
  night: { km: 'យប់', en: 'Night' },
  cycle: { km: 'វដ្ដ', en: 'Cycle' },
  // (the weather setting: a note under it for the one chosen)
  weather: { km: 'អាកាសធាតុ', en: 'Weather' },
  wSeason: { km: 'តាមរដូវ', en: 'By season' },
  wClear: { km: 'មេឃស្រឡះ', en: 'Clear' },
  wRainy: { km: 'ភ្លៀងញឹកញាប់', en: 'Rainy' },
  wStormy: { km: 'ព្យុះភ្លៀង', en: 'Stormy' },
  wSeasonNote: { km: 'ភ្លៀងនៅរដូវវស្សា ហើយស្ងួតពីខែធ្នូដល់ខែមេសា', en: 'Rain in the wet season, dry from December to April' },
  wClearNote: { km: 'គ្មានភ្លៀងទេ មានតែខ្យល់បក់រំភើយ', en: 'No rain, only a light breeze' },
  wRainyNote: { km: 'ភ្លៀងមួយមេ ប្រហែលរៀងរាល់ ១០ នាទីម្ដង', en: 'A shower every ten minutes or so' },
  wStormyNote: { km: 'ព្យុះផ្គររន្ទះញឹកញាប់ មានភ្លៀងធម្មតាចន្លោះ', en: 'Thunderstorms often, showers in between' },
  // (the moon's path, under the weather: sky/palette.ts `moonPath`; a note under it for the one chosen)
  moonPath: { km: 'ព្រះច័ន្ទ', en: 'Moon' },
  moonHigh: { km: 'ខ្ពស់លើមេឃ', en: 'High' },
  moonLow: { km: 'ទាបលើភ្នំ', en: 'Low' },
  moonHighNote: { km: 'រះពីទិសខាងកើត ឡើងខ្ពស់លើមេឃ ហើយលិចនៅទិសខាងលិច៖ ពន្លឺរបស់វាបំភ្លឺគ្រប់ភូមិ', en: 'It rises in the east, climbs high and sets in the west: its light reaches every village' },
  moonLowNote: { km: 'នៅទាបលើជួរភ្នំខាងជើង ដូចក្នុងគំនូរផែនទី៖ ភ្នំខ្លះអាចបាំងវា', en: "It stays low over the northern hills, as in the map's painting: some hills can hide it" },
  // (the graphics setting: a note under it for the choice, graphics.ts; Auto's names the level in use)
  graphics: { km: 'គុណភាពរូបភាព', en: 'Graphics' },
  gAuto: { km: 'ស្វ័យប្រវត្តិ', en: 'Auto' },
  gLow: { km: 'ទាប', en: 'Low' },
  gMedium: { km: 'មធ្យម', en: 'Medium' },
  gHigh: { km: 'ខ្ពស់', en: 'High' },
  gMax: { km: 'អតិបរមា', en: 'Max' },
  gAutoNote: { km: 'ជ្រើសរើសកម្រិតដែលឧបករណ៍នេះដើររលូន ហើយបន្ថយពេលវាយឺត។ ឥឡូវ៖ {level}', en: 'Picks what runs smoothly on this device, and goes lower if it gets slow. Now: {level}' },
  gLowNote: { km: 'លឿនបំផុត៖ រូបភាពមិនសូវច្បាស់ ប្លុកសាមញ្ញ គ្មានពន្លឺចែងចាំង មានតែស្រមោលរបស់ដែលនៅស្ងៀម', en: 'Fastest: a softer picture, plain blocks, no glow, shadows of still things only' },
  gMediumNote: { km: 'ច្បាស់ តែបន្ថយភាពច្បាស់ពេលផែនទីដើរយឺត', en: 'Sharp, softer only while the map runs slow' },
  gHighNote: { km: 'ច្បាស់ជានិច្ច ទោះផែនទីរលូនតិចជាងមុន', en: 'Always sharp, even if the map runs less smoothly' },
  gMaxNote: { km: 'ច្បាស់ជានិច្ច គែមរលោងជាងមុន ស្រមោលរលូន', en: 'Always sharp, smoother edges and shadows' },
  calm: { km: 'បន្ថយចលនា', en: 'Reduce motion' },
  calmNote: { km: 'កាមេរ៉ានៅស្ងៀម ហោះខ្លីៗ', en: 'Still camera, short flights' },
  easyFly: { km: 'ហោះងាយស្រួល', en: 'Easy flying' },
  // (a key stays with its word: no-break spaces)
  easyFlyNote: { km: 'ខ្លែងហោះ និងបាឡុងរក្សាកម្ពស់៖ S ឡើង W ចុះ', en: 'Glider and balloon hold their height: S climbs, W dives' },
  // (on a touch screen: the stick of the touch controls, roam/touch.ts)
  easyFlyNoteTouch: { km: 'ខ្លែងហោះ និងបាឡុងរក្សាកម្ពស់៖ ទាញដងបញ្ជាមកក្រោយដើម្បីឡើង រុញទៅមុខដើម្បីចុះ', en: 'Glider and balloon hold their height: pull the stick back to climb, push to dive' },
  // (the mini-map while roaming: shown, only its caption, a button for the big map, or hidden: minimap.ts)
  miniMap: { km: 'ផែនទីតូច', en: 'Mini-map' },
  mmShowChoice: { km: 'បង្ហាញ', en: 'Show' },
  mmButtonChoice: { km: 'តែប៊ូតុង', en: 'Button' },
  mmHideChoice: { km: 'លាក់', en: 'Hide' },
  miniMapShowNote: { km: 'ផែនទីតូចនៅជ្រុងខាងលើស្ដាំ ពេលដើរលេង', en: 'The small map in the top right corner while you roam' },
  miniMapButtonNote: { km: 'នៅសល់តែប៊ូតុង «ផែនទី» សម្រាប់បើកផែនទីធំ', en: 'Only the Map button stays, for the big map' },
  miniMapHideNote: { km: 'លាក់ទាំងស្រុង។ ចុច M ដើម្បីបើកផែនទីធំ', en: 'Hidden completely. M still opens the big map' },
  // (the keys of the mode, bottom left while roaming: hud.ts)
  keyHelp: { km: 'ជំនួយគ្រាប់ចុច', en: 'Key help' },
  keyHelpNote: { km: 'គ្រាប់ចុចនៅជ្រុងខាងក្រោមឆ្វេង។ ចុច ? ដើម្បីមើលទាំងអស់', en: 'The keys in the bottom left corner. ? shows them all' },
  // (back on the page, the browser still holds the sound: the card that asks for a tap, ui.ts)
  soundHeld: { km: 'សំឡេងបានផ្អាក', en: 'The sound is paused' },
  soundHeldNote: { km: 'ប៉ះទីនេះដើម្បីបើកសំឡេងវិញ', en: 'Tap here to turn it back on' },
  // (game pad: the held card's note while the pad is in use — a browser may not count a pad's press as the click the
  // sound needs, a key or a click it does —, the Controller group on the Play tab (ui.ts), the story's hint (story.ts))
  soundHeldPadNote: { km: 'ចុចគ្រាប់ចុចណាមួយ ឬចុចទីនេះ ដើម្បីបើកសំឡេង', en: 'Press any key or click here to turn it on' },
  padHead: { km: 'ឧបករណ៍បញ្ជាហ្គេម', en: 'Controller' },
  padRumble: { km: 'ការញ័រ', en: 'Vibration' },
  padRumbleNote: { km: 'ឧបករណ៍បញ្ជាញ័រ៖ ពេលចុះចត ពេលត្រីស៊ីនុយ និងពេលផ្គរលាន់', en: 'The controller shakes: landings, a fish biting, thunder' },
  padNone: { km: 'ឧបករណ៍បញ្ជា PS5 ឬ Xbox ក៏ប្រើបានដែរ៖ ភ្ជាប់វា រួចចុចប៊ូតុងណាមួយ', en: 'A PS5 or Xbox controller works too: connect it and press a button' },
  padOther: { km: 'បានភ្ជាប់', en: 'Connected' },
  padOnMap: { km: 'លើផែនទី', en: 'On the map' },
  padOnFoot: { km: 'ពេលដើរ', en: 'On foot' },
  padPlaces: { km: 'ទីកន្លែង', en: 'Places' },
  padPick: { km: 'ជ្រើសរើស', en: 'Pick' },
  padBack: { km: 'ត្រឡប់ក្រោយ', en: 'Back' },
  padTabs: { km: 'ផ្ទាំង', en: 'Tabs' },
  padWalk: { km: 'ដើរ', en: 'Walk' },
  padRun: { km: 'រត់', en: 'Run' },
  padLook: { km: 'មើលជុំវិញ', en: 'Look around' },
  padZoom: { km: 'ពង្រីក · បង្រួម', en: 'Zoom' },
  padJump: { km: 'លោត', en: 'Jump' },
  padUse: { km: 'ប្រើ', en: 'Use' },
  padMenu: { km: 'ម៉ឺនុយអ្នករុករក', en: 'Explorer menu' },
  padToMap: { km: 'ត្រឡប់ទៅផែនទី', en: 'Back to the map' },
  padTools: { km: 'ភ្លើង កាមេរ៉ា សំពះ', en: 'Light, camera, greet' },
  padBigMap: { km: 'ផែនទីធំ', en: 'Big map' },
  padRamp: { km: 'ជម្រាលខ្លែងហោះ', en: 'Glider ramp' },
  stHintPad: { km: 'ដើម្បីបន្ត', en: 'to continue' },
  language: { km: 'ភាសា', en: 'Language' },
  m: { km: 'ម', en: 'm' },
  km: { km: 'គ.ម', en: 'km' },
  // The credits button by the gear and its page (the names: credits.ts).
  credits: { km: 'អ្នករួមចំណែក', en: 'Credits' },
  // The story before the map (story/story.ts; its own words are in story/beats.ts), and its row in the settings:
  stStory: { km: 'រឿងរ៉ាវរបស់យើង', en: 'Our story' },
  stStoryNote: { km: 'ពាក្យផ្ដាំជូនយុវជនខ្មែរ', en: 'A message to the young people of Cambodia' },
  stWatch: { km: 'មើល', en: 'Watch' },
  support: { km: 'គាំទ្រហ្គេមនេះ', en: 'Support the game' },
  supportNote: { km: 'ចូលចិត្តហ្គេមនេះទេ? ទិញកាហ្វេមួយកែវឱ្យខ្ញុំ ដើម្បីជួយខ្ញុំបន្តកសាងវា', en: 'Enjoying the game? Buy me a coffee to help me keep building it' },
  supportGo: { km: 'ទិញកាហ្វេឱ្យខ្ញុំ', en: 'Buy me a coffee' },
  // (the corner's coffee button asks with a card: ui/_support.ts)
  supportLong: { km: 'បើអ្នកចូលចិត្តមរតកអង្គរ សូមទិញកាហ្វេមួយកែវឱ្យខ្ញុំ។ វាជួយខ្ញុំបន្តកសាងពិភពនេះ។', en: 'If you enjoy Angkor Heritage, buy me a coffee. It helps me keep building this world.' },
  supportLater: { km: 'ពេលក្រោយ', en: 'Maybe later' },
  // (game pad: its press on "Buy me a coffee" cannot open a new tab — a browser opens one only from a click, a tap or a
  // key —, so the card stays and says so: ui/ask.ts, _support.ts)
  supportPadLink: { km: 'កម្មវិធីរុករកបើកទំព័រនេះបាន លុះត្រាតែអ្នកចុចដោយកណ្ដុរ ឬប៉ះលើអេក្រង់៖ សូមចុចប៊ូតុងពណ៌មាស ឬចូលទៅកាន់ {url}', en: 'Your browser opens this page only from a click or a tap: click the gold button, or visit {url}' },
  // (the sound on / off switch, first in the settings' sound part: ui.ts)
  soundOn: { km: 'បើកសំឡេង', en: 'Sound on' },
  stSkip: { km: 'រំលង', en: 'Skip' },
  stPrev: { km: 'មុន', en: 'Back' },
  stNext: { km: 'បន្ទាប់', en: 'Next' },
  stHint: { km: 'ចុចដើម្បីបន្ត', en: 'Click to continue' },
  stHintTouch: { km: 'ប៉ះដើម្បីបន្ត', en: 'Tap to continue' },
  stStart: { km: 'តោះ ទៅមើលទាំងអស់គ្នា …', en: "Let's all go and see …" },
  stBegin: { km: 'ចាប់ផ្ដើម', en: 'Start' },
  stSoundOn: { km: 'សូមបើកសំឡេង', en: 'Turn your sound on' },
  stEmpire: { km: 'អាណាចក្រខ្មែរ', en: 'Khmer Empire' },
  stAngkor: { km: 'អង្គរ', en: 'Angkor' },
  stYear: { km: 'ប្រហែលឆ្នាំ ៩០០ គ.ស.', en: 'Around 900 CE' },
  stCredit: { km: 'ផែនទី៖ Jembezmamy, Wikimedia Commons (CC0)', en: 'Map: Jembezmamy, Wikimedia Commons (CC0)' },
  // Mini-map and the big map (M) while roaming: minimap.ts.
  mmOpen: { km: 'បើកផែនទី (M)', en: 'Open the map (M)' },
  mmClose: { km: 'បិទផែនទី (M)', en: 'Close the map (M)' },
  mmTitle: { km: 'ផែនទីខ្ពង់រាប', en: 'Highland Map' },
  mmSub: { km: 'ជ្រើសរើសទីកន្លែងមួយ ផែនទីតូចនឹងបង្ហាញផ្លូវទៅ', en: 'Pick a place, and your mini-map shows the way' },
  mmHere: { km: 'អ្នកនៅទីនេះ', en: 'You are here' },
  mmYou: { km: 'អ្នក', en: 'You' },
  mmTemple: { km: 'ប្រាសាទ', en: 'Temple' },
  mmRoad: { km: 'ផ្លូវ', en: 'Road' },
  mmRiver: { km: 'ទន្លេ', en: 'River' },
  mmNorth: { km: 'ជ', en: 'N' },
  mmArrived: { km: 'អ្នកបានមកដល់ហើយ', en: 'You have arrived' },
  mmTarget: { km: 'គោលដៅ', en: 'Target' },
  mmPick: { km: 'ជ្រើសរើសទីកន្លែងមួយ ដើម្បីកំណត់ជាគោលដៅរបស់អ្នក។', en: 'Pick a place to set it as your target.' },
  mmHeading: { km: 'កំពុងទៅ{name} ចម្ងាយ {d}៖ តាមព្រួញមាសលើផែនទីតូចរបស់អ្នក។', en: 'Heading for {name}, {d} away: follow the gold arrow on your mini-map.' },
  mmHeadFor: { km: 'ទៅ{name}', en: 'Head for {name}' },
  mmIsTarget: { km: '{name}៖ គោលដៅរបស់អ្នក (ចុចម្ដងទៀតដើម្បីលុប)', en: '{name}: your target (click to clear)' },
  mmRamp: { km: 'ជម្រាលខ្លែងហោះ', en: 'Glider ramp' },
  mmTheRamp: { km: 'ជម្រាលខ្លែងហោះ', en: 'the glider ramp' },
  mmNearest: { km: 'ជម្រាលខ្លែងហោះជិតបំផុត', en: 'Nearest glider ramp' },
  mmNear: { km: 'ជិតបំផុត', en: 'Nearest' },
  mmBalloon: { km: 'បាឡុងខ្យល់ក្ដៅ', en: 'Hot air balloon' },
  mmTheBalloon: { km: 'បាឡុងខ្យល់ក្ដៅ', en: 'the hot air balloon' },
  // Roaming (roam/*). Keys stay as on the keyboard; a key stays with its word (no-break spaces).
  // The keys of each mode, bottom left (hud.ts):
  rDrag: { km: 'អូស', en: 'drag' },
  rLook: { km: 'មើលជុំវិញ', en: 'look' },
  rMove: { km: 'ដើរ', en: 'move' },
  rRun: { km: 'រត់', en: 'run' },
  rJump: { km: 'លោត', en: 'jump' },
  rEnterFly: { km: 'ចូល · ហោះ', en: 'enter · fly' },
  rUseFly: { km: 'ប្រើ · ហោះ', en: 'use · fly' },
  rSitLie: { km: 'អង្គុយ · ដេក', en: 'sit · lie down' },
  rRamp: { km: 'ជម្រាលខ្លែងហោះ', en: 'glider ramp' },
  rEmotes: { km: 'កាយវិការ', en: 'emotes' },
  rSteer: { km: 'បត់', en: 'steer' },
  rTurn: { km: 'បត់', en: 'turn' },
  rDive: { km: 'ចុះ', en: 'dive' },
  rChuteDive: { km: 'ចុះលឿន', en: 'dive' },
  rBrake: { km: 'បន្ថយល្បឿន', en: 'brake' },
  rClimb: { km: 'ឡើង', en: 'climb' },
  rFast: { km: 'លឿន', en: 'fast' },
  rFaster: { km: 'បង្កើនល្បឿន', en: 'faster' },
  rSlowerClimb: { km: 'បន្ថយល្បឿន · ឡើង', en: 'slower · climb' },
  rLetGo: { km: 'លែងដៃ', en: 'let go' },
  rPaddle: { km: 'ចែវ', en: 'paddle' },
  rPhoto: { km: 'ថតរូប', en: 'photo' },
  rBurn: { km: 'បាញ់ភ្លើង · ឡើង', en: 'burner · climb' },
  rVent: { km: 'បើករន្ធខ្យល់ · ចុះ', en: 'vent · sink' },
  rBothBurners: { km: 'បាញ់ភ្លើងទាំងពីរ', en: 'both burners' },
  rLandOut: { km: 'ចុះចត · ចេញ', en: 'land · step out' },
  // Prompts ("E  Enter Angkor Wat": the key, two spaces, what it does) and short messages:
  rEnter: { km: 'ចូល{name}', en: 'Enter {name}' },
  rSoon: { km: '{name} — ឆាប់ៗនេះ', en: '{name} — coming soon' },
  rNotOpen: { km: '{name} មិនទាន់បើកនៅឡើយទេ — ឆាប់ៗនេះ', en: '{name} is not open yet — coming soon' },
  rBoard: { km: 'ឡើងទូក', en: 'Board the boat' },
  rAshore: { km: 'ឡើងគោក', en: 'Step ashore' },
  rFly: { km: 'ជិះខ្លែងហោះ', en: 'Fly the hang glider' },
  rBalloon: { km: 'ជិះបាឡុងខ្យល់ក្ដៅ', en: 'Ride the hot air balloon' },
  // The rope swing on the Bayon's rim (roam/_swingRide.ts): sit on it, and get off.
  rSwing: { km: 'អង្គុយយោលលេង', en: 'Swing' },
  rSwingOff: { km: 'ចុះមកវិញ', en: 'Get off' },
  rLand: { km: 'ចុះចត', en: 'Land' },
  rStepOut: { km: 'ចេញពីកន្ត្រក', en: 'Step out' },
  // The parked balloon filling up before the ride (roam/balloon.ts).
  rInflating: { km: 'កំពុងបំប៉ោងបាឡុង · Space ឲ្យលឿន · Esc ឈប់', en: 'Inflating the balloon · Space faster · Esc stop' },
  // (game pad: the same while the pad is in use, in the prompt's "key  what" form: hud.ts draws Space as ✕, Esc as ○)
  rInflatingPad: { km: 'កំពុងបំប៉ោងបាឡុង  ·  Space  ឲ្យលឿន  ·  Esc  ឈប់', en: 'Inflating the balloon  ·  Space  faster  ·  Esc  stop' },
  rToBank: { km: 'ចែវចូលជិតច្រាំងបន្តិចទៀត', en: 'Paddle closer to the bank' },
  rMist: { km: 'អ័ព្ទក្រាស់ពេក មិនអាចទៅមុខទៀតបានទេ', en: 'The mist is too thick to go further' },
  rWindBack: { km: 'ខ្យល់បក់នាំអ្នកត្រឡប់ទៅរកប្រាសាទវិញ', en: 'The wind turns you back towards the temples' },
  rLetGoLand: { km: 'ហោះត្រឡប់មកលើដីសិន ទើបលែងដៃបាន', en: 'Fly back over the land first, then let go' },
  rThinAir: { km: 'ខ្យល់ស្ដើងណាស់នៅកម្ពស់នេះ', en: 'The air is thin up here' },
  // The hot air balloon (balloon.ts): where it will not come down, the mist at the edge, its keys on the first ride.
  rNoLand: { km: 'មិនអាចចុះនៅទីនេះបានទេ៖ រកដីរាបស្មើ និងទំនេរ', en: 'Not here: find flat, open ground' },
  rNoLandWater: { km: 'មិនអាចចុះលើទឹកបានទេ៖ រកដីរាបស្មើ និងទំនេរ', en: 'Not on the water: find flat, open ground' },
  rNoLandTemple: { km: 'មិនអាចចុះលើប្រាសាទបានទេ៖ រកដីរាបស្មើ និងទំនេរនៅក្បែរនោះ', en: 'Not on the temple: find flat, open ground nearby' },
  rNoLandTrees: { km: 'ដើមឈើច្រើនពេក៖ រកវាលទំនេរ', en: 'Too many trees here: find an open clearing' },
  rBalloonEdge: { km: 'ខ្យល់ស្ងប់នៅមាត់អ័ព្ទ៖ ឡើង ឬចុះ ដើម្បីរកខ្យល់ផ្សេង', en: 'The breeze dies at the mist: climb or sink to find another wind' },
  // (easy flying, as the hang glider; with it off, the real balloon)
  rBalloonKeys: {
    km: 'បាឡុងខ្យល់ក្ដៅ៖ A / D បត់ · S ឬ Space ឡើង (បាញ់ភ្លើង) · W ចុះ (បើករន្ធខ្យល់) · Shift លឿន · វារក្សាកម្ពស់ដោយខ្លួនឯង',
    en: 'Hot air balloon: A / D turn · S or Space climb (the burner) · W descend (the vent) · Shift fast · it holds its height by itself',
  },
  rBalloonTouch: {
    km: 'បាឡុងខ្យល់ក្ដៅ៖ ដងបញ្ជាទៅឆ្វេង ឬស្ដាំ ដើម្បីបត់ · ទាញមកក្រោយ ឬសង្កត់ «លោត» ដើម្បីឡើង រុញទៅមុខដើម្បីចុះ · វារក្សាកម្ពស់ដោយខ្លួនឯង',
    en: 'Hot air balloon: stick left / right turns · pull back or hold Jump to climb, push to descend · it holds its height by itself',
  },
  rBalloonReal: {
    km: 'បាឡុងខ្យល់ក្ដៅ៖ S / Space បាញ់ភ្លើងដើម្បីឡើង (Shift៖ ភ្លើងទាំងពីរ) · W បើករន្ធខ្យល់ដើម្បីចុះ · A / D បត់ · ខ្យល់នាំអ្នកទៅ ហើយប្ដូរទិសតាមកម្ពស់',
    en: 'Hot air balloon: S / Space burner (climb; with Shift both burners) · W vent (sink) · A / D turn · the wind carries you, and turns with height',
  },
  rBalloonRealTouch: {
    km: 'បាឡុងខ្យល់ក្ដៅ៖ ទាញដងបញ្ជាមកក្រោយ ឬសង្កត់ «លោត» ដើម្បីបាញ់ភ្លើង (ទាញហួសរង្វង់៖ ភ្លើងទាំងពីរ) · រុញទៅមុខដើម្បីបើករន្ធខ្យល់ · ទៅឆ្វេង ឬស្ដាំ ដើម្បីបត់ · ខ្យល់នាំអ្នកទៅ',
    en: 'Hot air balloon: pull the stick back or hold Jump for the burner (past its ring: both burners) · push to vent · left / right turns · the wind carries you',
  },
  // (game pad: the same while the pad is in use; the left stick ← → ↓ (pulled back) ↑ (pushed); {jump} ✕ / A,
  // {fast} R2 / RT: the pad's own names, glyphs.ts `padName`)
  rBalloonPad: {
    km: 'បាឡុងខ្យល់ក្ដៅ៖ ដងបញ្ជា ← → បត់ · ↓ ឬ {jump} ឡើង (បាញ់ភ្លើង) · ↑ ចុះ (បើករន្ធខ្យល់) · {fast} លឿន · វារក្សាកម្ពស់ដោយខ្លួនឯង',
    en: 'Hot air balloon: stick ← → turn · ↓ or {jump} climb (the burner) · ↑ descend (the vent) · {fast} fast · it holds its height by itself',
  },
  rBalloonRealPad: {
    km: 'បាឡុងខ្យល់ក្ដៅ៖ ដងបញ្ជា ↓ / {jump} បាញ់ភ្លើងដើម្បីឡើង ({fast}៖ ភ្លើងទាំងពីរ) · ↑ បើករន្ធខ្យល់ដើម្បីចុះ · ← → បត់ · ខ្យល់នាំអ្នកទៅ ហើយប្ដូរទិសតាមកម្ពស់',
    en: 'Hot air balloon: stick ↓ / {jump} burner (climb; with {fast} both burners) · ↑ vent (sink) · ← → turn · the wind carries you, and turns with height',
  },
  // The hang glider's keys on the first flight (hangGlider.ts): easy flying, the real glider; on touch the stick and Jump.
  rGliderKeys: { km: 'ខ្លែងហោះ៖ A / D បត់ · S ឡើង · W ចុះ · Shift លឿន · Space លែងដៃ', en: 'Hang glider: A / D turn · S climb · W dive · Shift fast · Space let go' },
  rGliderTouch: { km: 'ខ្លែងហោះ៖ ដងបញ្ជាទៅឆ្វេង ឬស្ដាំ ដើម្បីបត់ · ទាញមកក្រោយដើម្បីឡើង រុញទៅមុខដើម្បីចុះ · «លោត» ដើម្បីលែងដៃ', en: 'Hang glider: stick left / right turns · pull back to climb, push to dive · Jump lets go' },
  rGliderReal: {
    km: 'ខ្លែងហោះ៖ A / D បត់ · W បង្កើនល្បឿន · S បន្ថយល្បឿន · ឡើងកម្ពស់តាមច្រាំងថ្មចោទ ឬហោះវិលក្នុងសំឡីពណ៌មាស',
    en: 'Hang glider: A / D turn · W faster · S slower · climb along cliffs, or circle in the golden seed fluff',
  },
  rGliderRealTouch: {
    km: 'ខ្លែងហោះ៖ ដងបញ្ជាទៅឆ្វេង ឬស្ដាំ ដើម្បីបត់ · រុញទៅមុខឱ្យលឿន ទាញមកក្រោយឱ្យយឺត · ឡើងកម្ពស់តាមច្រាំងថ្មចោទ ឬហោះវិលក្នុងសំឡីពណ៌មាស',
    en: 'Hang glider: stick left / right turns · push faster, pull back slower · climb along cliffs, or circle in the golden seed fluff',
  },
  // (game pad: the same while the pad is in use; the left stick ← → ↓ (pulled back) ↑ (pushed); {jump} ✕ / A,
  // {fast} R2 / RT: the pad's own names, glyphs.ts `padName`)
  rGliderPad: { km: 'ខ្លែងហោះ៖ ដងបញ្ជា ← → បត់ · ↓ ឡើង · ↑ ចុះ · {fast} លឿន · {jump} លែងដៃ', en: 'Hang glider: stick ← → turn · ↓ climb · ↑ dive · {fast} fast · {jump} let go' },
  rGliderRealPad: {
    km: 'ខ្លែងហោះ៖ ដងបញ្ជា ← → បត់ · ↑ បង្កើនល្បឿន · ↓ បន្ថយល្បឿន · ឡើងកម្ពស់តាមច្រាំងថ្មចោទ ឬហោះវិលក្នុងសំឡីពណ៌មាស',
    en: 'Hang glider: stick ← → turn · ↑ faster · ↓ slower · climb along cliffs, or circle in the golden seed fluff',
  },
  // The explorer's tools (tools.ts; the list's words are these in lower case):
  rTools: { km: 'ឧបករណ៍', en: 'Tools' },
  rToolsAria: { km: 'ឧបករណ៍របស់អ្នករុករក', en: "The explorer's tools" },
  rLantern: { km: 'ចង្កៀងគោម', en: 'Lantern' },
  rTorch: { km: 'ចន្លុះ', en: 'Torch' },
  rFlashlight: { km: 'ពិល', en: 'Flashlight' },
  rCamera: { km: 'កាមេរ៉ា', en: 'Camera' },
  rSelfie: { km: 'ទូរស័ព្ទសែលហ្វី', en: 'Selfie phone' },
  rAlbum: { km: 'អាល់ប៊ុមរូបថត', en: 'Photo album' },
  rAllKeys: { km: 'គ្រាប់ចុចទាំងអស់', en: 'All keys' },
  // (game pad: the explorer menu's button for the list of them while the pad is in use, roam/_explorerMenu.ts; with the keys it says rAllKeys)
  rAllButtons: { km: 'ប៊ូតុងទាំងអស់', en: 'All buttons' },
  rKeys: { km: 'គ្រាប់ចុច', en: 'Keys' },
  rPutAway: { km: 'ទុក{name}វិញ', en: '{name} put away' },
  rHandsPaddle: { km: 'ដៃកំពុងកាន់ច្រវ៉ា (កាមេរ៉ា និងទូរស័ព្ទប្រើបាននៅទីនេះ៖ 4, 5)', en: 'Hands on the paddle (the camera and the phone work here: 4, 5)' },
  rHandsBar: { km: 'ដៃកំពុងកាន់របារ (កាមេរ៉ា និងទូរស័ព្ទប្រើបាននៅទីនេះ៖ 4, 5)', en: 'Hands on the bar (the camera and the phone work here: 4, 5)' },
  rHandsBurner: { km: 'ដៃកំពុងកាន់ខ្សែភ្លើង (កាមេរ៉ា និងទូរស័ព្ទប្រើបាននៅទីនេះ៖ 4, 5)', en: 'Hands on the burner line (the camera and the phone work here: 4, 5)' },
  rBeamOn: { km: 'ពិល · {beam} (O ដើម្បីប្ដូរ)', en: 'Flashlight · {beam} (O to change)' },
  rBeam: { km: 'ពិល៖ {beam}', en: 'Flashlight: {beam}' },
  rBeamAhead: { km: 'ចាំងត្រង់ទៅមុខ', en: 'straight ahead' },
  rBeamMouse: { km: 'ចាំងតាមកណ្ដុរ', en: 'follows the mouse' },
  rStickOn: { km: 'ដងសែលហ្វី៖ បើក (រំកិលដើម្បីពន្លូត)', en: 'Selfie stick: on (wheel slides it out)' },
  rStickOff: { km: 'ដងសែលហ្វី៖ បិទ (កាន់ដោយលាតដៃ)', en: 'Selfie stick: off (at arm’s length)' },
  // (game pad: roaming, roam/tools.ts and _rest.ts; {keys}: the pad's own name for L1, "L1" or "LB")
  rStickOnPad: { km: 'ដងសែលហ្វី៖ បើក (ចុច {keys} ដើម្បីពន្លូត)', en: 'Selfie stick: on ({keys} slides it out)' },
  rAsleepPad: { km: 'លង់លក់បាត់ហើយ… ចុចប៊ូតុងណាក៏បាន ដើម្បីដាស់', en: 'Fast asleep… any button wakes him' },
  rHatOn: { km: 'ពាក់មួក', en: 'Hat on' },
  rHatOff: { km: 'ដោះមួក', en: 'Hat off' },
  // (he kneels to pray at a shrine: roam/_pray.ts; the prompt in front of one, "E  Pray")
  rPray: { km: 'ថ្វាយបង្គំ', en: 'Paying respect' },
  // (J sits him down, L lies him down, watching the sky: roam/_rest.ts)
  rSitting: { km: 'អង្គុយមើលមេឃ', en: 'Sitting, watching the sky' },
  rLying: { km: 'ដេកផ្ងារមើលមេឃ', en: 'Lying back, watching the sky' },
  rAsleep: { km: 'លង់លក់បាត់ហើយ… ចុចអ្វីក៏បាន ដើម្បីដាស់', en: 'Fast asleep… any key wakes him' },
  rAwake: { km: 'ភ្ញាក់ហើយ', en: 'Awake' },
  rGetUp: { km: 'ក្រោកឈរ', en: 'Get up' },
  rLieBack: { km: 'ដេកផ្ងារ', en: 'Lie back' },
  rSitUp: { km: 'ក្រោកអង្គុយ', en: 'Sit up' },
  rRestWater: { km: 'មិនអាចអង្គុយ ឬដេកក្នុងទឹកបានទេ', en: 'Not in the water' },
  rRestSteep: { km: 'ដីនៅទីនេះមិនរាបស្មើល្មមទេ', en: 'The ground is not flat enough here' },
  rRestRoom: { km: 'គ្មានកន្លែងទំនេរល្មមនៅទីនេះទេ', en: 'Not enough room here' },
  rPrayHere: { km: 'ថ្វាយបង្គំ', en: 'Pray' },
  rOutfitIs: { km: 'សម្លៀកបំពាក់៖ {name}', en: 'Outfit: {name}' },
  rFaceIs: { km: 'ទឹកមុខ៖ {name}', en: 'Face: {name}' },
  rGestureIs: { km: 'សញ្ញាដៃ៖ {name}', en: 'Gesture: {name}' },
  rNoCamera: { km: 'ឈុតនេះគ្មានកាមេរ៉ាទេ (G ប្ដូរសម្លៀកបំពាក់)', en: 'No camera with this outfit (G changes the outfit)' },
  rLookGear: { km: 'ឈុតអ្នករុករក', en: 'explorer gear' },
  rLookPack: { km: 'កាបូបស្ពាយ', en: 'day pack' },
  rLookNoScarf: { km: 'គ្មានក្រមា', en: 'no scarf' },
  rLookTemple: { km: 'ឈុតប្រពៃណី', en: 'temple clothes' },
  rFaceNeutral: { km: 'ធម្មតា', en: 'neutral' },
  rFaceHappy: { km: 'សប្បាយចិត្ត', en: 'happy' },
  rFaceDetermined: { km: 'ម៉ឺងម៉ាត់', en: 'determined' },
  rFaceSurprised: { km: 'ភ្ញាក់ផ្អើល', en: 'surprised' },
  rFaceCurious: { km: 'ចង់ដឹងចង់ឃើញ', en: 'curious' },
  rFaceFocused: { km: 'ផ្ចិតផ្ចង់', en: 'focused' },
  rPeace: { km: 'សញ្ញាសន្តិភាព', en: 'peace sign' },
  rThumbsUp: { km: 'លើកមេដៃ', en: 'thumbs up' },
  rNoGesture: { km: 'គ្មានសញ្ញាដៃ', en: 'no gesture' },
  // All the keys (?, tools.ts) and the camera's and the phone's key lines (photo.ts):
  rExplorer: { km: 'អ្នករុករក', en: 'Explorer' },
  rView: { km: 'ទិដ្ឋភាព', en: 'View' },
  rSelfieHead: { km: 'សែលហ្វី', en: 'Selfie' },
  rBeamKeys: { km: 'ចាំងទៅមុខ / តាមកណ្ដុរ', en: 'beam ahead / mouse' },
  rWave: { km: 'គ្រវីដៃ', en: 'wave' },
  rCheer: { km: 'អបអរ', en: 'cheer' },
  rLookUp: { km: 'ងើយមើល', en: 'look up' },
  rPeek: { km: 'លបមើល', en: 'peek' },
  rSit: { km: 'អង្គុយ', en: 'sit' },
  rLieDown: { km: 'ដេកផ្ងារ', en: 'lie down' },
  // The explorer menu (I, roam/_explorerMenu.ts): its titles are rMoves, rOutfit, rFace.
  rMoves: { km: 'ចលនា', en: 'Moves' },
  rOnFootOnly: { km: 'បានតែពេលដើរ (ដៃកំពុងជាប់)', en: 'on foot only (hands busy)' },
  rMenuKey: { km: 'ចលនា សម្លៀកបំពាក់ ទឹកមុខ', en: 'moves, outfits, faces' },
  rPrayAt: { km: 'លុតជង្គង់ថ្វាយបង្គំ នៅទីសក្ការបូជា', en: 'kneel and pray at a shrine' },
  rHat: { km: 'មួក', en: 'hat' },
  rOutfit: { km: 'សម្លៀកបំពាក់', en: 'outfit' },
  rFace: { km: 'ទឹកមុខ', en: 'face' },
  rLookRound: { km: 'មើលជុំវិញគាត់', en: 'look round him' },
  rWheel: { km: 'រំកិល', en: 'wheel' },
  rZoom: { km: 'ពង្រីក · បង្រួម', en: 'zoom' },
  rBigMap: { km: 'ផែនទីធំ', en: 'big map' },
  // (what E does close by: the golden figures, the swing, the balloon)
  rCloseBy: { km: 'នៅក្បែរ', en: 'Close by' },
  rClick: { km: 'ចុច', en: 'click' },
  rTake: { km: 'ថត', en: 'take' },
  rTakePhoto: { km: 'ថតរូប', en: 'take a photo' },
  rStow: { km: 'ទុកវិញ', en: 'put away' },
  rDragLook: { km: 'អូសដើម្បីមើល', en: 'drag to look' },
  rWheelZoom: { km: 'រំកិលដើម្បីពង្រីក', en: 'wheel to zoom' },
  rMovePhone: { km: 'ផ្លាស់ទីទូរស័ព្ទ', en: 'move the phone' },
  rDragPhone: { km: 'អូសដើម្បីផ្លាស់ទីទូរស័ព្ទ', en: 'drag to move the phone' },
  rReach: { km: 'ជិត / ឆ្ងាយ', en: 'closer / further' },
  rStick: { km: 'ដងសែលហ្វី', en: 'selfie stick' },
  rGesture: { km: 'សញ្ញាដៃ', en: 'gesture' },
  rHolding: { km: 'កាន់{name}', en: 'holding the {name}' },
  // The festivals (festival/_banner.ts): under the title card, and a toast when roaming starts.
  festKicker: { km: 'ពិធីបុណ្យ', en: 'Festival' },
  festWater: { km: 'បុណ្យអុំទូក', en: 'Water Festival' },
  festWaterNote: { km: 'ប្រណាំងទូកងលើបឹងធំ · បណ្ដែតប្រទីប · សំពះព្រះខែ', en: 'Boat races on the great lake · lit floats · saluting the moon' },
  festNewYear: { km: 'បុណ្យចូលឆ្នាំខ្មែរ', en: 'Khmer New Year' },
  festNewYearNote: { km: 'ភ្នំខ្សាច់ · ទង់ជ័យ · ល្បែងប្រជាប្រិយនៅភូមិ', en: 'Sand stupas · flags · folk games in the village' },
  // The touch controls (touch.ts):
  rtUse: { km: 'ប្រើ', en: 'Use' },
  rtJump: { km: 'លោត', en: 'Jump' },
  rtShutter: { km: 'ថតរូប', en: 'Take a photo' },
  rtClose: { km: 'ទុកកាមេរ៉ាវិញ', en: 'Put the camera away' },
  // The photo album's own words (src/game/Photos.ts `ALBUM_WORDS_EN`; passed in roam/photo.ts):
  alRec: { km: 'ថតរូប', en: 'Photo' },
  alModePhoto: { km: 'រូបថត', en: 'Photo' },
  alModeSelfie: { km: 'សែលហ្វី', en: 'Selfie' },
  alShutter: { km: 'ថតសែលហ្វី', en: 'Take the selfie' },
  alButton: { km: 'អាល់ប៊ុម', en: 'Album' },
  alButtonN: { km: 'អាល់ប៊ុម · {n}', en: 'Album · {n}' },
  alButtonTip: { km: 'រូបថតរបស់អ្នក', en: 'Your photos' },
  alHeading: { km: 'អាល់ប៊ុមរូបថត', en: 'Photo album' },
  alClose: { km: 'បិទ (Esc)', en: 'Close (Esc)' },
  alCountOne: { km: 'រូបថត {n} សន្លឹក', en: '1 photo' },
  alCountN: { km: 'រូបថត {n} សន្លឹក', en: '{n} photos' },
  alEmpty: { km: 'មិនទាន់មានរូបថតនៅឡើយទេ។ ចុច {camera} ដើម្បីលើកកាមេរ៉ា ឬ {selfie} ដើម្បីថតសែលហ្វី។', en: 'No photos yet. Press {camera} to raise the camera, or {selfie} for a selfie.' },
  alPhotoAlt: { km: 'រូបថត {when}', en: 'Photo, {when}' },
  alDownload: { km: 'ទាញយក', en: 'Download' },
  alDelete: { km: 'លុប', en: 'Delete' },
  alAll: { km: 'រូបថតទាំងអស់', en: 'All photos' },
  alSaved: { km: 'បានរក្សាទុកក្នុងអាល់ប៊ុម', en: 'Saved to the album' },
  // (the maker's mark in the corner of every new photo)
  alMarkTitle: { km: 'មរតកអង្គរ', en: 'Angkor Heritage' },
  alMarkBy: { km: 'បង្កើតដោយក្ដីស្រឡាញ់ ❤️ ពី នៅ សុចិត្រា', en: 'Made with ❤️ By Sochetra NOV' },
  // The album's nature book and temple passport (roam/_book.ts, _bookUi.ts; names and facts: roam/_bookData.ts):
  bkTabs: { km: 'ផ្នែកនៃអាល់ប៊ុម', en: 'Album sections' },
  bkPhotos: { km: 'រូបថត', en: 'Photos' },
  bkBook: { km: 'សៀវភៅធម្មជាតិ', en: 'Nature book' },
  bkPassport: { km: 'លិខិតឆ្លងដែន', en: 'Passport' },
  bkPassportTitle: { km: 'លិខិតឆ្លងដែនប្រាសាទ', en: 'Temple passport' },
  bkBookHint: { km: 'ថតរូបសត្វ រុក្ខជាតិ និងមនុស្ស ដើម្បីបំពេញទំព័រ — ចូលទៅជិត ឬពង្រីករូប។', en: 'Photograph animals, plants and people to fill its pages — get close, or zoom in.' },
  bkPassportHint: {
    km: 'ដើរទៅដល់ប្រាសាទ ទីកន្លែងលាក់កំបាំងក្នុងព្រៃ និងភូមិនានា ដើម្បីទទួលបានត្រា។ លុតជង្គង់ថ្វាយបង្គំនៅទីសក្ការៈ ដើម្បីទទួលបានត្រាផ្កាឈូក។',
    en: 'Walk to the temples, the jungle’s hidden places and the villages for their stamps. Kneel and pray at a shrine for a lotus seal.',
  },
  bkNew: { km: 'ថ្មីក្នុងសៀវភៅធម្មជាតិ៖ {name}', en: 'New in your nature book: {name}' },
  bkStamped: { km: 'ត្រាថ្មីក្នុងលិខិតឆ្លងដែន៖ {name}', en: 'Passport stamp: {name}' },
  bkLotus: { km: 'ត្រាផ្កាឈូក៖ {name}', en: 'Lotus seal: {name}' },
  bkLotusLabel: { km: 'ថ្វាយបង្គំ', en: 'Prayed' },
  bkNotYet: { km: 'មិនទាន់ឃើញ', en: 'Not seen yet' },
  bkLook: { km: 'រកមើល៖ {where}', en: 'Look {where}' },
  bkFirstSeen: { km: 'ឃើញលើកដំបូង {date}', en: 'First seen {date}' },
  bkNear: { km: 'ក្បែរ {name}', en: 'near {name}' },
  bkShots: { km: 'រូបថត៖ {n}', en: 'Photos: {n}' },
  bkBack: { km: 'ត្រឡប់ក្រោយ', en: 'Back' },
  bkTemples: { km: 'ប្រាសាទ', en: 'Temples' },
  bkSites: { km: 'ក្នុងព្រៃ', en: 'In the jungle' },
  bkVisited: { km: 'បានទៅដល់ {date}', en: 'Visited {date}' },
  bkPrayedOn: { km: 'បានថ្វាយបង្គំ {date}', en: 'Prayed {date}' },
  bkNotVisited: { km: 'មិនទាន់ទៅដល់', en: 'Not visited yet' },
  bkNoPicture: { km: 'មិនទាន់មានរូប', en: 'No picture yet' },
  // People on the map (people/): what they say to the explorer in a small bubble.
  pplHello: { km: 'ជម្រាបសួរ', en: 'Hello!' },
  // Hidden gold (treasure/): the figures' names (lower case: they go in sentences), the prompt, the messages and the counter.
  tgApsara: { km: 'អប្សរាមាស', en: 'golden apsara' },
  tgNaga: { km: 'នាគមាស', en: 'golden naga' },
  tgGaruda: { km: 'គ្រុឌមាស', en: 'golden garuda' },
  tgBayonFace: { km: 'ព្រះភក្ត្របាយ័នមាស', en: 'golden Bayon face' },
  tgSingha: { km: 'សិង្ហមាស', en: 'golden lion' },
  tgNandi: { km: 'គោនន្ទិមាស', en: 'golden Nandi bull' },
  tgLotus: { km: 'ផ្កាឈូកមាស', en: 'golden lotus' },
  tgKinnari: { km: 'កិន្នរីមាស', en: 'golden kinnari' },
  tgTurtle: { km: 'អណ្ដើកមាស', en: 'golden turtle' },
  tgMakara: { km: 'មករមាស', en: 'golden makara' },
  tgRabbit: { km: 'ទន្សាយមាស', en: 'golden rabbit' },
  tgHanuman: { km: 'ហនុមានមាស', en: 'golden Hanuman' },
  tgElephant: { km: 'ដំរីមាស', en: 'golden elephant' },
  tgPeacock: { km: 'ក្ងោកមាស', en: 'golden peacock' },
  tgHamsa: { km: 'ហង្សមាស', en: 'golden hamsa' },
  tgPick: { km: 'រើស{name}', en: 'Pick up the {name}' },
  // (the key list, roam/tools.ts)
  tgPickAny: { km: 'រើសរូបចម្លាក់មាស', en: 'pick up a golden figure' },
  tgFound: { km: 'រកឃើញ{name} — {n} / {total}', en: '{name} found — {n} / {total}' },
  tgAll: { km: 'អ្នករកឃើញរូបចម្លាក់មាសទាំង {total} ហើយ!', en: 'You found all {total} golden figures!' },
  tgCount: { km: 'រូបចម្លាក់មាសដែលបានរកឃើញ', en: 'Golden figures found' },
  // ── Each new pass adds its words right under its own line here (keys with its prefix), never elsewhere ──
  // Greeting (gr…): roam/_greet.ts, people/_greetBack.ts
  grGreet: { km: 'សំពះ', en: 'greet' },
  // (what people say back, in a bubble over their heads: people/_greetBack.ts)
  grHello: { km: 'ជម្រាបសួរ', en: 'Hello!' },
  grHowAreYou: { km: 'សុខសប្បាយទេ?', en: 'How are you?' },
  grHi: { km: 'សួស្ដី', en: 'Hi!' },
  grElder: { km: 'សុខសប្បាយទេ ចៅ?', en: 'Are you well, dear?' },
  grWelcome: { km: 'អញ្ជើញ!', en: 'Please, come in!' },
  grKid: { km: 'សួស្ដី!', en: 'Hello!' },
  grKidBong: { km: 'សួស្ដីបង!', en: 'Hi there!' },
  grMonk: { km: 'សូមឱ្យសុខសប្បាយ', en: 'May you be well' },
  // (visitors from abroad say it in their own words)
  grVisitor: { km: 'Hello!', en: 'Hello!' },
  grVisitorHi: { km: 'Hi!', en: 'Hi!' },
  // Fishing (fi…): roam/_fishing*.ts
  fiFish: { km: 'ស្ទូចត្រី', en: 'Fish' },
  // (the prompts while he fishes: F again puts the pole away; at a bite F, Space, a click or the touch button strikes)
  fiStop: { km: 'ឈប់ស្ទូច', en: 'Stop fishing' },
  fiStrike: { km: 'ទាញ!', en: 'Strike!' },
  // (the first time in a visit: how it goes)
  fiHowTo: { km: 'ស្ទូចត្រី៖ រង់ចាំកូនបណ្ដែតលិច រួចចុច F ឬ Space ដើម្បីទាញ · W A S D ឬ E ដើម្បីឈប់', en: 'Fishing: wait for the float to go under, then F or Space to strike · W A S D or E to stop' },
  fiHowToTouch: { km: 'ស្ទូចត្រី៖ រង់ចាំកូនបណ្ដែតលិច រួចចុច «ទាញ!» · រុញដងបញ្ជា ដើម្បីឈប់', en: 'Fishing: wait for the float to go under, then tap Strike! · push the stick to stop' },
  // (game pad: the same while the pad is in use; {strike} the d-pad's ↓ (F), {jump} ✕ / A (Space), {use} □ / X (E):
  // the pad's own names, glyphs.ts `padName`)
  fiHowToPad: { km: 'ស្ទូចត្រី៖ រង់ចាំកូនបណ្ដែតលិច រួចចុច {strike} ឬ {jump} ដើម្បីទាញ · រុញដងបញ្ជា ឬចុច {use} ដើម្បីឈប់', en: 'Fishing: wait for the float to go under, then {strike} or {jump} to strike · the stick or {use} to stop' },
  // (why not here: paddling, fast water, a fall ahead, no open water to cast to)
  fiSlowDown: { km: 'ឈប់ចែវសិន ទើបអាចស្ទូចបាន', en: 'Stop paddling first' },
  fiTooFast: { km: 'ទឹកហូរខ្លាំងពេក មិនអាចស្ទូចបានទេ', en: 'The water runs too fast to fish here' },
  fiFalls: { km: 'ជិតទឹកធ្លាក់ពេក', en: 'Too close to the falls' },
  fiNoRoom: { km: 'គ្មានទឹកទំនេរ សម្រាប់បោះសន្ទូចទេ', en: 'No open water to cast into' },
  // (what happens at the float)
  fiGotAway: { km: 'ត្រីរួចបាត់ហើយ', en: 'It got away' },
  fiEarly: { km: 'លឿនពេក — ត្រីភ័យហែលបាត់ហើយ', en: 'Too soon — it swam off' },
  // (the catch: "ត្រីរៀល — Trey riel · 12 cm", then he lets it go)
  fiCaught: { km: '{km} — {say} · {cm} ស.ម.', en: '{km} — {say} · {cm} cm' },
  // (its page in the nature book, filled by a catch: roam/_bookUi.ts)
  fiFirstCaught: { km: 'ស្ទូចបានលើកដំបូង {date}', en: 'First caught {date}' },
  fiCaughtMeta: { km: 'ស្ទូចបាន {n} ដង · ធំជាងគេ {cm} ស.ម.', en: 'Caught: {n} · biggest {cm} cm' },
  // Snow (sn…): sky/snow.ts, sky/weather.ts, the settings' weather choice
  snSnow: { km: 'ព្រិល', en: 'Snow' },
  snSnowNote: { km: 'ក្ដីសុបិន៖ នៅអង្គរ មិនដែលមានព្រិលធ្លាក់ទេ', en: 'A dream: it never snows at Angkor' },
  // The market (mk…): hamlet/_market.ts, people/_sceneMarket.ts
  mkMarket: { km: 'ផ្សារ', en: 'Market' },
  // (the sellers' calls, in their bubbles)
  mkFreshFish: { km: 'ត្រីស្រស់ៗ!', en: 'Fresh fish!' },
  mkCheap: { km: 'ថោកៗ!', en: 'Cheap, cheap!' },
  mkWhatBuy: { km: 'ទិញអីដែរបង?', en: 'What are you buying?' },
  mkLook: { km: 'អញ្ជើញមើលសិនបង!', en: 'Come and have a look!' },
  mkGreens: { km: 'បន្លែស្រស់ៗ!', en: 'Fresh greens!' },
  mkFruit: { km: 'ផ្លែឈើផ្អែមៗ!', en: 'Sweet fruit!' },
  mkNoodles: { km: 'នំបញ្ចុកឆ្ងាញ់ៗ!', en: 'Tasty num banh chok!' },
  mkSugar: { km: 'ស្ករត្នោតថ្មីៗ!', en: 'New palm sugar!' },
  mkCakes: { km: 'នំខ្មែរឆ្ងាញ់ៗ!', en: 'Khmer cakes, tasty!' },
  mkCane: { km: 'ទឹកអំពៅត្រជាក់ៗ!', en: 'Cold sugarcane juice!' },
  mkGrill: { km: 'សាច់អាំងក្ដៅៗ!', en: 'Hot grilled skewers!' },
  mkKrama: { km: 'ក្រមាល្អៗ!', en: 'Fine kramas!' },
  mkFlowers: { km: 'ផ្កាឈូកសម្រាប់វត្ត!', en: 'Lotus for the pagoda!' },
  // (the buyers bargaining)
  mkHowMuch: { km: 'ប៉ុន្មាន?', en: 'How much?' },
  mkLower: { km: 'ចុះថ្លៃបន្តិចបានទេ?', en: 'A little cheaper?' },
  mkThanks: { km: 'អរគុណ!', en: 'Thank you!' },
  // The palm sugar (ps…): hamlet/_palmSugar.ts, people/_scenePalmSugar.ts
  psPalmSugar: { km: 'ស្ករត្នោត', en: 'Palm sugar' },
  psTaste: { km: 'សាកភ្លក់ស្ករត្នោតមើល!', en: 'Have a taste of our palm sugar!' },
  psSell: { km: 'ទិញស្ករត្នោតទេបង? មានទឹកត្នោតស្រស់ផង!', en: 'Palm sugar, bong? Fresh palm juice too!' },
  // The east village (ev…): hamlet/_eastVillage.ts, people/_sceneEastVillage.ts
  evVillage: { km: 'ភូមិត្នោត', en: 'Sugar Palm Village' },
  // (speech bubbles: a grandmother's greeting, the children calling to the explorer, the shopkeeper)
  evEaten: { km: 'ញ៉ាំបាយហើយឬនៅ ចៅ?', en: 'Have you eaten yet, dear?' },
  evKids: { km: 'សួស្ដី! សួស្ដី!', en: 'Hello! Hello!' },
  evShop: { km: 'ត្រូវការអីខ្លះ?', en: 'What can I get you?' },
  // Kulen's people and the picnic place (kn…): hamlet/_kulenPicnic.ts, people/_sceneKulen.ts
  knPicnic: { km: 'កន្លែងកម្សាន្តភ្នំគូលែន', en: 'Kulen picnic place' },
  // (the painted sign where the picnic trail comes in: hamlet/_knSign.ts)
  knSign: { km: 'ទឹកធ្លាក់ភ្នំគូលែន', en: 'Kulen Waterfall' },
  knSignSub: { km: 'សូមស្វាគមន៍', en: 'Welcome' },
  // Behind Angkor Wat (bh…): hamlet/_backHamlet.ts, people/_sceneBack.ts
  bhHamlet: { km: 'ភូមិក្រោយអង្គរវត្ត', en: 'The hamlet behind Angkor Wat' },
  // (the juice seller at the sala, people/_sceneBackFolk.ts)
  bhCoconut: { km: 'ដូងខ្ចីត្រជាក់ៗ! អញ្ជើញ!', en: 'Cold young coconuts! Come, have one!' },
  // (the market's sellers, people/_sceneBackMarket.ts; the others call the east market's mk… words)
  bhBreakfast: { km: 'នំបញ្ចុក បបរក្ដៅៗ!', en: 'Num banh chok, hot rice porridge!' },
  bhKrok: { km: 'នំគ្រក់ក្ដៅៗ!', en: 'Hot num krok!' },
  // The Kulen reclining Buddha (rb…): landmarks/kulen.ts
  rbBuddha: { km: 'ព្រះអង្គធំ', en: 'The reclining Buddha' },
  // (the name board on the gate at the foot of his rock: landmarks/_kulenBuddha.ts)
  rbGate: { km: 'វត្តព្រះអង្គធំ', en: 'Wat Preah Ang Thom' },
  rbGateSub: { km: 'ភ្នំគូលែន', en: 'Phnom Kulen' },
  // Kites (kt…): people/_sceneKites.ts
  ktKite: { km: 'ខ្លែងឯក', en: 'Khleng ek kite' },
  // (speech bubbles: the grandfather flying his khleng ek, the eldest of the children in the west)
  ktHear: { km: 'ឮសំឡេងឯកទេ?', en: 'Can you hear the ek sing?' },
  ktHighest: { km: 'ខ្លែងខ្ញុំហើរខ្ពស់ជាងគេ!', en: 'My kite flies the highest!' },
  // The journal and mini-map for the new places (jn…): roam/_book*.ts, roam/_stamps.ts, ui/minimap.ts
  jnNew: { km: 'ថ្មី', en: 'New' },
  // (the new places on the mini-map and the big map, ui/_minimapSpots.ts: the name, then as said in a sentence; the village's is evVillage)
  jnMarket: { km: 'ផ្សារព្រឹក', en: 'Morning market' },
  jnTheMarket: { km: 'ផ្សារព្រឹក', en: 'the morning market' },
  jnPalmSugar: { km: 'ខ្ទមស្ករត្នោត', en: 'Palm sugar hut' },
  jnThePalmSugar: { km: 'ខ្ទមស្ករត្នោត', en: 'the palm sugar hut' },
  jnFalls: { km: 'ទឹកធ្លាក់ភ្នំគូលែន', en: 'Kulen waterfall' },
  jnTheFalls: { km: 'ទឹកធ្លាក់ភ្នំគូលែន', en: 'the Kulen waterfall' },
  jnBuddha: { km: 'ព្រះអង្គធំ', en: 'Reclining Buddha' },
  jnTheBuddha: { km: 'ព្រះអង្គធំ', en: 'the reclining Buddha' },
  jnHamlet: { km: 'ភូមិក្រោយអង្គរវត្ត', en: 'Hamlet behind Angkor Wat' },
  jnTheHamlet: { km: 'ភូមិក្រោយអង្គរវត្ត', en: 'the hamlet behind Angkor Wat' },
  // (the passport's third section, roam/_bookUi.ts: after the temples and the jungle, bkTemples / bkSites)
  jnVillages: { km: 'ភូមិ និងទីសក្ការៈ', en: 'Villages and holy places' },
  // Perf (pf…) and the world size (ws…)
  pfNote: { km: 'ល្បឿន', en: 'Speed' },
  wsEdge: { km: 'ចុងផែនទី', en: 'Edge of the map' },
  // Leaving roaming asks first (rl…): roam/_leave.ts
  rlTitle: { km: 'ត្រឡប់ទៅផែនទីវិញ?', en: 'Back to the map?' },
  rlNote: { km: 'អ្នករុករកនឹងឈប់ដើរលេង។ ចង់ដើរលេងទៀត ត្រូវលោតចុះម្ដងទៀត។', en: 'Your explorer stops roaming. To come back, you jump in again.' },
  rlStay: { km: 'បន្តរុករក', en: 'Keep exploring' },
  rlGo: { km: 'ត្រឡប់ទៅផែនទី', en: 'Back to the map' },
  // Buying, eating and drinking (by…): roam/_shop*.ts, people/_saleBack.ts, hamlet/_shops.ts
  byBuyAt: { km: 'ទិញ — {name}', en: 'Buy — {name}' },
  byBuy: { km: 'ទិញនៅតូប', en: 'Buy at a stall' },
  byClosed: { km: '{name} បិទហើយ', en: '{name} is closed now' },
  byAsk: { km: 'ទិញអីដែរ បង?', en: 'What would you like?' },
  byClose: { km: 'បិទ', en: 'Close' },
  byPurse: { km: 'កាបូបលុយ', en: 'Purse' },
  byPaid: { km: 'បានបង់ {price}', en: 'Paid {price}' },
  byEatNow: { km: 'ញ៉ាំឥឡូវនេះ', en: 'Eat it now' },
  byDrinkNow: { km: 'ផឹកឥឡូវនេះ', en: 'Drink it now' },
  byKeep: { km: 'ទុកពេលក្រោយ', en: 'Keep for later' },
  byBagFull: { km: 'កាបូបពេញហើយ', en: 'Bag full' },
  byShort: { km: 'លុយមិនគ្រប់ទេ — ព្រលឹមស្អែកមានលុយហោប៉ៅថ្មី', en: 'Not enough riel: more pocket money comes at dawn' },
  byThanks: { km: 'អរគុណបង!', en: 'Thank you!' },
  byYum: { km: 'ឆ្ងាញ់!', en: 'Delicious!' },
  byFresh: { km: 'ស្រស់ស្រាយ!', en: 'So refreshing!' },
  byKept: { km: 'បានទុក {name} ({n}/{max})', en: 'Kept for later: {name} ({n}/{max})' },
  byBag: { km: 'ក្នុងកាបូប', en: 'In my bag' },
  byBagEmpty: { km: 'មិនទាន់មានអ្វីទុកទេ', en: 'Nothing kept yet' },
  byEatThis: { km: 'ញ៉ាំ {name}', en: 'Eat: {name}' },
  byDrinkThis: { km: 'ផឹក {name}', en: 'Drink: {name}' },
  byEatKept: { km: 'ញ៉ាំ ឬផឹកអ្វីដែលបានទុក', en: 'Eat or drink what you kept' },
  byOnFoot: { km: 'ញ៉ាំ និងផឹក ពេលដើរលើដី', en: 'Eat and drink on foot' },
  bySitUp: { km: 'អង្គុយឡើងសិន (J) ទើបញ៉ាំបាន', en: 'Sit up first (J) to eat' },
  byPocket: { km: 'លុយហោប៉ៅថ្មី៖ {n}', en: 'Fresh pocket money: {n}' },
  // The floating village's market (fv…): village/_fvMarket.ts, people/_sceneVillageMarket.ts (the sellers also call the east market's mk… words)
  fvPrahok: { km: 'ប្រហុកឆ្ងាញ់ៗ!', en: 'Good prahok!' },
  fvGrill: { km: 'ត្រីអាំងក្ដៅៗ!', en: 'Hot grilled fish!' },
  fvCoffee: { km: 'កាហ្វេទឹកកក!', en: 'Iced coffee!' },
  fvBoatFruit: { km: 'ចេក ស្វាយ ទិញទេបង?', en: 'Bananas, mangoes — buy some?' },
  fvBoatGreens: { km: 'ត្រកួនស្រស់ៗ!', en: 'Fresh morning glory!' },
  fvBoatFish: { km: 'ត្រីទើបចាប់ថ្មីៗ!', en: 'Fish, just caught!' },
  fvBoatNoodles: { km: 'គុយទាវក្ដៅៗ!', en: 'Hot noodle soup!' },
  // The settings' resolution and battery saver (res…, battery…): ui/ui.ts; the sizes: resolution.ts. Auto's button is gAuto.
  resolution: { km: 'កម្រិតភាពច្បាស់', en: 'Resolution' },
  // (the note under the sizes: Auto's names the size drawn now; a picked size says what it means)
  resAutoNote: { km: 'ទៅតាមកម្រិតគុណភាពរូបភាព។ ឥឡូវ៖ {size}', en: 'Follows the graphics level. Now: {size}' },
  resFullNote: { km: 'គ្រប់ចំណុចនៃអេក្រង់៖ ច្បាស់បំផុត តែធ្ងន់ម៉ាស៊ីនបំផុត', en: 'Every dot of the screen: the sharpest, but the most work' },
  resWholeNote: { km: 'ភីកសែលមួយស្មើ {n} × {n} ចំណុចលើអេក្រង់៖ គែមប្លុកនៅតែមុតច្បាស់', en: 'Each pixel is {n} × {n} screen dots: crisp blocks' },
  resSmoothNote: { km: 'ពង្រីកឱ្យពេញអេក្រង់យ៉ាងរលូន៖ មុតតិចជាងបន្តិច', en: 'Scaled up smoothly: a little softer' },
  // (a size kept from another window size or screen: none of these is pressed)
  resOtherNote: { km: 'ជម្រើសមុនរបស់អ្នក។ ឥឡូវ៖ {size}', en: 'Your earlier pick. Now: {size}' },
  // (the mark on a whole step's size: its tooltip, and the size's name for a screen reader)
  resSharp: { km: 'មុតច្បាស់', en: 'Sharp' },
  resSharpSize: { km: '{size} មុតច្បាស់', en: '{size}, sharp' },
  battery: { km: 'សន្សំថ្ម', en: 'Battery saver' },
  batteryNote: { km: 'យ៉ាងច្រើន ៣០ រូបភាពក្នុងមួយវិនាទី៖ ឧបករណ៍មិនសូវក្ដៅ ហើយថ្មប្រើបានយូរជាង', en: 'At most 30 frames a second: cooler and longer on battery' },
  // The settings' fog: one slider, its thickness 0‥150 (ui/ui.ts; sky/fogLevel.ts `fogNow.amount`); the step follows the graphics level.
  fog: { km: 'អ័ព្ទ', en: 'Fog' },
  fogAmount: { km: 'កម្រាស់', en: 'Thickness' },
  // (under the slider: at 0 the mist still hides the map's cut edges)
  fogNote: { km: 'ទៅឆ្វេង អ័ព្ទស្ដើង ទៅស្ដាំ អ័ព្ទក្រាស់ ១០០ ជាអ័ព្ទធម្មតារបស់ហ្គេម។ គែមផែនទីនៅតែមានអ័ព្ទជានិច្ច', en: "Left thins the fog, right thickens it; 100 is the game's own. The mist always stays at the map's edges" },
  // ── The new things to do (docs/ideas.md): each adds its words right under its own line, keys with its prefix ──
  // The calendar of events (when…): roam/_calendar*.ts, calendar.ts
  whenTitle: { km: 'ប្រតិទិនព្រឹត្តិការណ៍', en: 'Calendar of events' },
  whenButton: { km: 'ប្រតិទិន', en: 'Calendar' },
  whenOpenAria: { km: 'ប្រតិទិនព្រឹត្តិការណ៍៖ អ្វីកំពុងប្រារព្ធ និងពេលណា (9)', en: 'Calendar of events: what is on, and when (9)' },
  whenClose: { km: 'បិទ', en: 'Close' },
  whenNow: { km: 'ឥឡូវនេះ', en: 'Now' },
  whenToday: { km: 'ថ្ងៃនេះ', en: 'Today' },
  whenAhead: { km: 'ពិធីបុណ្យខាងមុខ', en: 'Festivals ahead' },
  whenSeasons: { km: 'តាមរដូវ', en: 'Seasons' },
  whenNoneNow: { km: 'ពេលនេះមិនទាន់មានព្រឹត្តិការណ៍ទេ', en: 'Nothing on just now' },
  whenNoneToday: { km: 'ថ្ងៃនេះគ្មានអ្វីទៀតទេ', en: 'Nothing more today' },
  whenNoneAhead: { km: 'មិនទាន់ឃើញក្នុងប៉ុន្មានឆ្នាំខាងមុខទេ', en: 'Not in the years ahead' },
  whenShow: { km: 'បង្ហាញលើផែនទី', en: 'Show on map' },
  whenShown: { km: 'ជាគោលដៅ', en: 'On your map' },
  whenWait: { km: 'រង់ចាំដល់ពេល', en: 'Wait for it' },
  whenWaiting: { km: 'កំពុងរង់ចាំ…', en: 'Waiting…' },
  whenHeld: { km: 'ពេលវេលាកំពុងឈប់ ({mode})។ ដើម្បីឱ្យវាដើរ៖ {path}', en: 'Time stands still ({mode}). To let it run: {path}' },
  whenRuns: { km: 'នៅពេលម៉ោងដើរ', en: 'once time runs' },
  whenFoot: { km: '9 ឬ Esc ដើម្បីបិទ', en: '9 or Esc closes' },
  // (the time of day an event comes, and until when it goes on: by the clock's part of the day)
  whenAtDawn: { km: 'ពេលព្រលឹម', en: 'at dawn' },
  whenAtMorning: { km: 'ពេលព្រឹក', en: 'in the morning' },
  whenAtNoon: { km: 'ពេលថ្ងៃត្រង់', en: 'around midday' },
  whenAtAfternoon: { km: 'ពេលរសៀល', en: 'in the afternoon' },
  whenAtDusk: { km: 'ពេលល្ងាច', en: 'at dusk' },
  whenAtEvening: { km: 'ពេលយប់', en: 'after dark' },
  whenAtMidnight: { km: 'ពេលពាក់កណ្ដាលអធ្រាត្រ', en: 'around midnight' },
  whenAtLate: { km: 'មុនភ្លឺ', en: 'before dawn' },
  whenTilDawn: { km: 'រហូតដល់ព្រលឹម', en: 'until dawn' },
  whenTilMorning: { km: 'រហូតដល់ពេលព្រឹក', en: 'until mid-morning' },
  whenTilNoon: { km: 'រហូតដល់ថ្ងៃត្រង់', en: 'until midday' },
  whenTilAfternoon: { km: 'រហូតដល់ពេលរសៀល', en: 'until mid-afternoon' },
  whenTilDusk: { km: 'រហូតដល់ពេលល្ងាច', en: 'until dusk' },
  whenTilEvening: { km: 'រហូតដល់ពេលយប់', en: 'until evening' },
  whenTilMidnight: { km: 'រហូតដល់ពាក់កណ្ដាលអធ្រាត្រ', en: 'until midnight' },
  whenTilLate: { km: 'រហូតដល់មុនភ្លឺ', en: 'until before dawn' },
  whenInSec: { km: '{n} វិនាទីទៀត', en: 'in {n} s' },
  whenInMin: { km: '{n} នាទីទៀត', en: 'in {n} min' },
  whenInHm: { km: '{h} ម៉ោង {m} នាទីទៀត', en: 'in {h} h {m} min' },
  whenInH: { km: '{h} ម៉ោងទៀត', en: 'in {h} h' },
  whenSoon: { km: 'បន្តិចទៀតនេះ', en: 'any moment' },
  whenLeftSec: { km: 'នៅសល់ {n} វិនាទី', en: '{n} s left' },
  whenLeftMin: { km: 'នៅសល់ {n} នាទី', en: '{n} min left' },
  whenLeftDays: { km: 'នៅ {n} ថ្ងៃទៀតលើផែនទី', en: '{n} more days on the map' },
  whenLeftDay1: { km: 'នៅមួយថ្ងៃទៀតលើផែនទី', en: 'one more day on the map' },
  whenDays: { km: '{n} ថ្ងៃទៀតលើផែនទី', en: 'in {n} days of the map' },
  whenDay1: { km: 'ប្រហែលមួយថ្ងៃទៀតលើផែនទី', en: 'in about a day of the map' },
  whenPlay: { km: 'លេងប្រហែល {t} ទៀត', en: 'about {t} of play' },
  whenMin: { km: '{n} នាទី', en: '{n} min' },
  whenHm: { km: '{h} ម៉ោង {m} នាទី', en: '{h} h {m} min' },
  whenH: { km: '{h} ម៉ោង', en: '{h} h' },
  // (the next one in real life: the Khmer calendar's dates, roam/_calendarKhmer.ts)
  whenReal: { km: 'ក្នុងជីវិតពិត៖ {date}', en: 'In real life: {date}' },
  whenRealOn: { km: 'ក្នុងជីវិតពិត៖ កំពុងប្រារព្ធ ({date})', en: 'In real life: on now ({date})' },
  whenMonths: { km: 'មករា|កុម្ភៈ|មីនា|មេសា|ឧសភា|មិថុនា|កក្កដា|សីហា|កញ្ញា|តុលា|វិច្ឆិកា|ធ្នូ', en: 'January|February|March|April|May|June|July|August|September|October|November|December' },
  whenDate: { km: 'ថ្ងៃទី {d} ខែ{m} ឆ្នាំ {y}', en: '{d} {m} {y}' },
  whenDates: { km: 'ថ្ងៃទី {d1}–{d2} ខែ{m} ឆ្នាំ {y}', en: '{d1}–{d2} {m} {y}' },
  whenDates2: { km: 'ថ្ងៃទី {d1} ខែ{m1} – ថ្ងៃទី {d2} ខែ{m2} ឆ្នាំ {y}', en: '{d1} {m1} – {d2} {m2} {y}' },
  whenLunarMonths: { km: 'មិគសិរ|បុស្ស|មាឃ|ផល្គុន|ចេត្រ|ពិសាខ|ជេស្ឋ|អាសាឍ|ស្រាពណ៍|ភទ្របទ|អស្សុជ|កត្តិក|បឋមាសាឍ|ទុតិយាសាឍ', en: 'Migasir|Bos|Meak|Phalkun|Cheit|Pisakh|Jesth|Asadh|Srap|Phatrabot|Assoch|Kadeuk|First Asadh|Second Asadh' },
  whenLunar: { km: 'ថ្ងៃ{n}{phase} ខែ{month}', en: '{month}, {phase} moon, day {n}' },
  whenLunarFull: { km: 'ថ្ងៃ១៥កើត ខែ{month} (ពេញបូណ៌មី)', en: 'Full moon of {month}' },
  whenWax: { km: 'កើត', en: 'waxing' },
  whenWane: { km: 'រោច', en: 'waning' },
  // (the map's moment, under the title)
  whenRainy: { km: 'រដូវវស្សា', en: 'rainy season' },
  whenDry: { km: 'រដូវប្រាំង', en: 'dry season' },
  whenMoonDay: { km: 'ថ្ងៃ{n}{phase}', en: '{phase} moon, day {n}' },
  whenMoonFull: { km: 'ពេញបូណ៌មី', en: 'full moon' },
  // (the toasts as an event begins, and after waiting for one)
  whenKickNow: { km: 'ឥឡូវនេះ', en: 'Now on' },
  whenKickSoon: { km: 'ជិតដល់ពេលហើយ', en: 'About to begin' },
  whenCantWait: { km: 'មិនអាចរង់ចាំបានឥឡូវនេះទេ', en: "Can't wait for it just now" },
  // (where)
  whenAtLake: { km: 'បឹងធំ និងគូទឹកអង្គរវត្ត', en: "The great lake and Angkor Wat's moat" },
  whenAtFloating: { km: 'ភូមិបណ្ដែតទឹក', en: 'Floating village' },
  whenAtNewYear: { km: 'ភូមិបណ្ដែតទឹក និងអង្គរវត្ត', en: 'The floating village and Angkor Wat' },
  whenAtPagoda: { km: 'វត្តក្នុងភូមិ និងអង្គរវត្ត', en: 'The village pagoda and Angkor Wat' },
  whenAtPagodaOnly: { km: 'វត្តក្នុងភូមិ', en: 'The village pagoda' },
  whenAtAngkor: { km: 'មុខប្រាសាទអង្គរវត្ត', en: 'In front of Angkor Wat' },
  whenAtRiverGate: { km: 'ក្រោមក្លោងទ្វារទន្លេ', en: 'Below the River Gate' },
  whenAtValley: { km: 'ផ្លូវក្នុងជ្រលងភ្នំ', en: 'The valley road' },
  whenAtEastFields: { km: 'វាលស្រែខាងកើត', en: 'The east rice fields' },
  whenAtPaddies: { km: 'វាលស្រែក្បែរបឹង', en: 'The paddies by the lake' },
  // (the events: name, what happens, the toast as it begins)
  whenWaterBegins: { km: 'បុណ្យអុំទូកចាប់ផ្ដើមហើយ', en: 'The Water Festival has begun' },
  whenNewYearBegins: { km: 'សួស្ដីឆ្នាំថ្មី! បុណ្យចូលឆ្នាំចាប់ផ្ដើមហើយ', en: 'Happy New Year! Khmer New Year has begun' },
  whenChant: { km: 'សូត្រមន្តពេលព្រលឹម', en: 'Monks chanting at dawn' },
  whenChantNote: { km: 'ព្រះសង្ឃសូត្រធម៌ជាភាសាបាលី', en: 'The monks chant their Pali prayers' },
  whenChantBegins: { km: 'ព្រះសង្ឃចាប់ផ្ដើមសូត្រមន្តហើយ', en: 'The monks begin their dawn chant' },
  whenDrum: { km: 'ស្គរវត្តពេលល្ងាច', en: "The pagoda's drum at dusk" },
  whenDrumNote: { km: 'ស្គរធំ និងជួងសំរិទ្ធពីវត្ត', en: 'The skor drum and the bronze bell' },
  whenDrumBegins: { km: 'ស្គរវត្តលាន់ឮហើយ', en: "The pagoda's drum is sounding" },
  whenAlms: { km: 'ដាក់បាត្រ', en: 'Alms round (dak bat)' },
  whenAlmsNote: { km: 'ព្រះសង្ឃនិមន្តបិណ្ឌបាតពីវត្តចុះមកផ្សារ', en: 'A monk walks from the pagoda to the market for alms' },
  whenAlmsBegins: { km: 'ព្រះសង្ឃនិមន្តបិណ្ឌបាតហើយ', en: 'A monk sets out on his alms round' },
  whenAlmsBackNote: { km: 'ព្រះសង្ឃនៅព្រៃជិះកង់មកភូមិ ឈប់ទទួលចង្ហាន់នៅផ្សារ', en: 'The forest monk rides his bicycle to the hamlet, stopping at the market' },
  whenAlmsBackBegins: { km: 'ព្រះសង្ឃជិះកង់មកបិណ្ឌបាតហើយ', en: 'The forest monk rides in for alms' },
  whenAlmsAwNote: { km: 'ព្រះសង្ឃប្រាំអង្គកាន់បាត្រ និមន្តឡើងផ្លូវទៅអង្គរវត្ត', en: 'Five monks walk up the road to Angkor Wat with their alms bowls' },
  whenAlmsAwBegins: { km: 'ព្រះសង្ឃកាន់បាត្រនិមន្តឡើងទៅអង្គរវត្តហើយ', en: 'The monks walk up to Angkor Wat with their bowls' },
  whenAtRoadAw: { km: 'ផ្លូវឡើងទៅអង្គរវត្ត', en: 'The road up to Angkor Wat' },
  whenMarketNote: { km: 'ត្រី បន្លែ ផ្លែឈើ នំបញ្ចុក ទឹកអំពៅ', en: 'Fish, greens, fruit, num banh chok, cane juice' },
  whenMarketBegins: { km: 'ផ្សារព្រឹកបើកហើយ', en: 'The morning market is open' },
  whenMarketBack: { km: 'ផ្សារតូច', en: 'Little market' },
  whenMarketBackNote: { km: 'បបរ នំបញ្ចុក ផ្លែឈើ និងដូងខ្ចី', en: 'Rice porridge, num banh chok, fruit and coconuts' },
  whenMarketBackBegins: { km: 'ផ្សារតូចបើកហើយ', en: 'The little market is open' },
  whenBoats: { km: 'ផ្សារលើទូក', en: 'Boat market' },
  whenBoatsNote: { km: 'ស្ត្រីលក់ត្រី បន្លែ និងផ្លែឈើពីលើទូកតាមបណ្ដោយផែ', en: 'Women sell fish, greens and fruit from boats along the jetty' },
  whenBoatsBegins: { km: 'ទូកលក់ដូរមកចតហើយ', en: 'The market boats are in' },
  whenApsara: { km: 'របាំអប្សរា', en: 'Apsara dance' },
  whenApsaraNote: { km: 'អ្នករាំពាក់មកុដមាស ភ្លេងពិណពាទ្យ ពន្លឺគប់ភ្លើង', en: 'Dancers in golden mokot, a pinpeat ensemble, torchlight' },
  whenApsaraBegins: { km: 'របាំអប្សរាចាប់ផ្ដើមហើយ', en: 'The apsara dance has begun' },
  whenElephants: { km: 'ដំរីងូតទឹក', en: "The elephants' bath" },
  whenElephantsNote: { km: 'ដំរីមេ និងកូនចុះងូតទឹកក្នុងស្ទឹង', en: 'The cow and her calf bathe in the river' },
  whenElephantsBegins: { km: 'ដំរីកំពុងចុះទៅងូតទឹក', en: 'The elephants are going down to bathe' },
  whenMonkeys: { km: 'ស្វាឆ្លងផ្លូវ', en: 'Macaques crossing' },
  whenMonkeysNote: { km: 'ហ្វូងស្វាក្ដាមរត់ឆ្លងផ្លូវជាជួរ', en: 'The troop runs across the road in a line' },
  whenMonkeysBegins: { km: 'ហ្វូងស្វាកំពុងឆ្លងផ្លូវ', en: 'The macaques are crossing the road' },
  whenKites: { km: 'បង្ហោះខ្លែងឯក', en: 'Flying khleng ek' },
  whenKitesNote: { km: 'គ្រួសារបង្ហោះខ្លែងឯក សូរខ្លែងលាន់ពេញវាលស្រែ', en: 'Families fly khleng ek; their bows hum over the fields' },
  whenKitesBegins: { km: 'ខ្លែងឯកហោះឡើងហើយ', en: 'The khleng ek are up' },
  whenPlanting: { km: 'ស្ទូងស្រូវ', en: 'Rice planting' },
  whenPlantingNote: { km: 'កសិករស្ទូងកូនស្រូវក្នុងស្រែទឹក', en: 'Farmers plant out the seedlings in the flooded paddies' },
  whenPlantingBegins: { km: 'កសិករចុះស្ទូងស្រូវហើយ', en: 'The farmers are out planting' },
  whenHarvest: { km: 'ច្រូតស្រូវ', en: 'Rice harvest' },
  whenHarvestNote: { km: 'កសិករច្រូតស្រូវទុំពណ៌មាស ហើយលីកណ្ដាប់ស្រូវទៅផ្ទះ', en: 'Farmers reap the golden rice and carry the sheaves home' },
  whenHarvestBegins: { km: 'កសិករចុះច្រូតស្រូវហើយ', en: 'The farmers are out reaping' },
  // The bicycle (bike…): roam/_bike*.ts
  bikeRide: { km: 'ជិះកង់', en: 'Ride the bicycle' },
  bikeOff: { km: 'ចុះពីកង់', en: 'Get off' },
  bikeBell: { km: 'ចុចកណ្ដឹង', en: 'Ring the bell' },
  // (the touch jump button while he rides: short)
  bikeBellBtn: { km: 'កណ្ដឹង', en: 'Bell' },
  // (the key help while he rides, bottom left)
  bikePedal: { km: 'ធាក់ · ហ្វ្រាំង', en: 'Pedal · brake' },
  bikeSteer: { km: 'បត់', en: 'Steer' },
  bikeFast: { km: 'ធាក់ឱ្យលឿន', en: 'Pedal hard' },
  // (stopped before something low at his head's height: a stall's umbrella, an awning, a low branch; at the sey circle)
  bikeLow: { km: 'ទាបពេក ជិះកាត់មិនបានទេ', en: 'Too low to ride under' },
  bikeSey: { km: 'ក្មេងៗកំពុងលេងទាត់សី', en: 'The children are playing sey' },
  bikeUp: { km: 'ចុះពីកង់សិន ទើបដើរឡើងបាន', en: 'Get off the bicycle to climb up' },
  bikeDown: { km: 'ចុះពីកង់សិន ទើបដើរចុះបាន', en: 'Get off the bicycle to climb down' },
  bikeDeep: { km: 'ទឹកជ្រៅពេក ជិះកង់កាត់មិនបានទេ', en: 'Too deep to ride through' },
  bikeMap: { km: 'ចំណតកង់', en: 'Bicycles' },
  bikeTheMap: { km: 'ចំណតកង់', en: 'the bicycles' },
  // Riding the ox cart (cart…): roam/_cartRide.ts
  cartRide: { km: 'ជិះរទេះគោ', en: 'Ride the ox cart' },
  cartOff: { km: 'ចុះពីរទេះ', en: 'Hop off' },
  // (the farmer driving it, over his head: as he climbs on, as it leaves a stop with him, standing for the night, as he hops off)
  cartHello: { km: 'ឡើងមក ក្មួយ! អង្គុយឱ្យជាប់ណា', en: 'Climb aboard! Hold on tight' },
  cartGo: { km: 'តោះ ទៅមុខទៀត!', en: 'On we go!' },
  cartNight: { km: 'យប់ហើយ គោត្រូវសម្រាក', en: "It's late: the oxen need their rest" },
  cartBye: { km: 'ដើរលេងឱ្យសប្បាយណា ក្មួយ!', en: 'Enjoy your walk!' },
  // (the cart waiting for him in its way: the farmer asks for the way)
  cartPass: { km: 'សុំផ្លូវបន្តិចណា ក្មួយ!', en: 'Excuse us, may we pass?' },
  // Riding a water buffalo (buf…): roam/_buffalo*.ts
  bufRide: { km: 'ជិះក្របី', en: 'Ride the buffalo' },
  bufOff: { km: 'ចុះពីក្របី', en: 'Get off' },
  // (its keys, the first ride: keyboard, touch, game pad ({fast}: R2 / RT))
  bufKeys: { km: 'ជិះក្របី៖ W ដើរទៅមុខ · A / D បត់ · Shift លឿនបន្តិច · S ថយក្រោយ · E ចុះ', en: 'Riding the buffalo: W walk on · A / D turn · Shift a little faster · S back up · E get off' },
  bufTouch: { km: 'ជិះក្របី៖ រុញដងបញ្ជាទៅមុខដើម្បីដើរ (ហួសរង្វង់៖ លឿនបន្តិច) · ទៅឆ្វេង ឬស្ដាំ ដើម្បីបត់ · ទាញមកក្រោយដើម្បីថយក្រោយ', en: 'Riding the buffalo: push the stick to walk on (past its ring: a little faster) · left / right turns · pull back to back up' },
  bufPad: { km: 'ជិះក្របី៖ ដងបញ្ជា ↑ ដើរ · ← → បត់ · ↓ ថយក្រោយ · {fast} លឿនបន្តិច', en: 'Riding the buffalo: stick ↑ walk on · ← → turn · ↓ back up · {fast} a little faster' },
  // (what it will not do; the first stop to graze)
  bufDeep: { km: 'ទឹកជ្រៅពេក ក្របីមិនព្រមចុះទេ', en: 'Too deep: the buffalo won’t go in' },
  bufBuilt: { km: 'ក្របីមិនព្រមឡើងទីនោះទេ', en: 'The buffalo won’t climb up there' },
  bufNoOff: { km: 'ចុះនៅទីនេះមិនបានទេ៖ ជិះទៅដីគោក ឬទឹករាក់សិន', en: 'Can’t get off here: ride to dry land or shallow water first' },
  bufGraze: { km: 'ក្របីឈប់ស៊ីស្មៅបន្តិច…', en: 'The buffalo stops for a bite of grass…' },
  // (the key help, bottom left, while he rides; the turn and the look are rTurn, rLook)
  bufKeyWalk: { km: 'ដើរ · ថយក្រោយ', en: 'walk on · back up' },
  bufKeyFast: { km: 'លឿនបន្តិច', en: 'a little faster' },
  bufKeyOff: { km: 'ចុះពីក្របី', en: 'get off' },
  // The zip line (zip…): roam/_zip*.ts, jungle/_zipLine.ts
  zipRide: { km: 'ជិះខ្សែរអិល', en: 'Ride the zip line' },
  // (while riding, with Shift: he tucks his legs up and goes faster)
  zipFaster: { km: 'បង្កើនល្បឿន', en: 'Speed up' },
  // (the touch jump button while he is clipped in: hold it to tuck up and go faster)
  zipTouch: { km: 'លឿន', en: 'Faster' },
  // (as he clips in: which line of the chain)
  zipLineOf: { km: 'ខ្សែទី {n} នៃ {of}', en: 'Line {n} of {of}' },
  // (landed on the last platform)
  zipDone: { km: 'អស្ចារ្យណាស់!', en: 'What a ride!' },
  // (the mini-map's badge at the foot of the first stair, and "Heading for the zip line")
  zipMap: { km: 'ខ្សែរអិល', en: 'Zip line' },
  zipTheMap: { km: 'ខ្សែរអិល', en: 'the zip line' },
  // (the sign at the first stair's foot)
  zipSign: { km: 'ខ្សែរអិល', en: 'Zip line' },
  zipSignSub: { km: '៣ ខ្សែ កាត់ព្រៃ', en: '3 lines through the jungle' },
  // Climbing the sugar palm ladder (palm…): roam/_palmClimb.ts
  palmClimb: { km: 'ឡើងជណ្ដើរ', en: 'Climb the ladder' },
  palmBusy: { km: 'ពូកំពុងឡើងដើមត្នោតនេះ', en: 'The tapper is up this palm' },
  palmStorm: { km: 'ខ្យល់ព្យុះខ្លាំង កុំឡើងដើមត្នោត', en: 'Too stormy to climb' },
  palmKeys: { km: 'W ឡើង · S ចុះ', en: 'W climbs up · S climbs down' },
  palmKeysStick: { km: 'រុញទៅមុខដើម្បីឡើង ទាញមកក្រោយដើម្បីចុះ', en: 'Push forward to climb up, back to climb down' },
  palmOff: { km: 'ចុះពីជណ្ដើរ', en: 'Step off' },
  palmJump: { km: 'លោតចុះ', en: 'Jump off' },
  palmTooHigh: { km: 'ខ្ពស់ពេក លោតមិនបានទេ', en: 'Too high to jump' },
  palmSwap: { km: 'ប្ដូរបំពង់', en: 'Swap the tube' },
  palmNight: { km: 'ទឹកត្នោតស្រក់ចូលបំពង់ពេញមួយយប់ — ព្រឹកស្អែកសឹមមកយក', en: 'The juice drips into the tubes all night: come back in the morning' },
  palmNotFull: { km: 'បំពង់នេះទើបប្ដូរ មិនទាន់ពេញទេ', en: 'This tube was just changed: it is not full yet' },
  palmWait: { km: 'អ្នកផ្ទះកំពុងមកយកបំពង់', en: 'The family is coming for the tube' },
  // (speech bubbles: the cook thanks him and gives him a cup of fresh palm juice; the tapper calls across from his palm)
  palmThanks: { km: 'អរគុណណាក្មួយ!', en: 'Thank you, dear!' },
  palmGift: { km: 'ទឹកត្នោតស្រស់មួយកែវ សម្រាប់ក្មួយ!', en: 'Fresh palm juice, for you!' },
  palmCallUp: { km: 'ប្រយ័ត្នរអិលណាក្មួយ!', en: 'Careful up there, it is slippery!' },
  palmCallTop: { km: 'ពីលើនេះមើលឃើញឆ្ងាយណាស់ មែនទេ?', en: 'You can see so far from up here, eh?' },
  // (the key help, bottom left, while he is on the ladder)
  palmKeyClimb: { km: 'ឡើង / ចុះ', en: 'climb up / down' },
  palmKeyQuick: { km: 'ឡើងលឿន', en: 'quicker' },
  palmKeyDown: { km: 'ចុះមកវិញ', en: 'climb down' },
  // The hammock (ham…): roam/_hammock.ts
  hamLie: { km: 'ដេកអង្រឹង', en: 'Lie in the hammock' },
  // (the prompt while he lies: "E  Get up · A/D  Swing it"; the toast as he gets in, on a pad or a touch screen with the stick's way)
  hamSwing: { km: 'យោលអង្រឹង', en: 'Swing it' },
  hamLying: { km: 'ដេកលេងលើអង្រឹង', en: 'Lazing in the hammock' },
  hamLyingStick: { km: 'ដេកលេងលើអង្រឹង · រុញដងបញ្ជាទៅឆ្វេង ឬស្ដាំ ដើម្បីយោល', en: 'Lazing in the hammock · push the stick left or right to swing' },
  // The alms round at dawn (dak…): roam/_dakBat.ts
  dakOffer: { km: 'ដាក់បាត្រព្រះសង្ឃ', en: 'Offer food to the monks' },
  // (near the monks with nothing to give: where to get it; no E)
  dakNeed: { km: 'ទិញបាយដំណើបនៅតូបផ្កា ផ្សារព្រឹក ដើម្បីដាក់បាត្រ', en: "To offer food to the monks, buy sticky rice at the morning market's flower stall" },
  dakUp: { km: 'ក្រោកឡើង', en: 'Get up' },
  dakDone: { km: 'បានដាក់បាត្រព្រះសង្ឃ (លើកទី {n})', en: 'You offered food to the monks ({n})' },
  dakMissed: { km: 'ព្រះសង្ឃនិមន្តហួសទៅហើយ', en: 'The monks have walked on' },
  // (the rice in his bag: a pick of it in "In my bag" or 6, the message once bought)
  dakKeepHint: { km: 'ទុកសម្រាប់ដាក់បាត្រព្រះសង្ឃពេលព្រឹកព្រលឹម', en: "Keep it for the monks' alms round at dawn" },
  dakKept: { km: '{name} នៅក្នុងកាបូបហើយ — រង់ចាំព្រះសង្ឃនិមន្តបិណ្ឌបាតពេលព្រឹក', en: "{name} is in your bag: wait by the road for the monks' alms round at dawn" },
  // (the calendar: the village round)
  dakCalNote: { km: 'ព្រះសង្ឃបីអង្គនិមន្តបិណ្ឌបាតតាមផ្លូវភូមិ អ្នកភូមិរង់ចាំដាក់បាត្រនៅមុខផ្ទះ', en: 'Three monks walk their alms round down the village street; families wait by their gates to give rice' },
  dakCalBegins: { km: 'ព្រះសង្ឃនិមន្តបិណ្ឌបាតហើយ', en: 'The monks set out on their alms round' },
  // A monk's blessing, the red string (bless…): roam/_blessing.ts
  blessAsk: { km: 'សុំពរពីព្រះសង្ឃ', en: 'Ask for a blessing' },
  blessUp: { km: 'ក្រោកឡើង', en: 'Get up' },
  blessDone: { km: 'ព្រះសង្ឃបានប្រទានពរដល់អ្នក។ អំបោះក្រហមនឹងការពារអ្នកគ្រប់ដំណើរ', en: 'A monk blessed you. The red string protects you on your travels.' },
  // (the monk's bubbles: the Pali blessing as Cambodians read it, in Khmer letters — Sabbītiyo…, Āyu vaṇṇo… —, then his words)
  blessPali1: { km: '♪ សព្វីតិយោ វិវជ្ជន្តុ សព្វរោគោ វិនស្សតុ', en: '♪ Sabbītiyo vivajjantu, sabbarogo vinassatu' },
  blessPali2: { km: '♪ មា តេ ភវត្វន្តរាយោ សុខី ទីឃាយុកោ ភវ', en: '♪ Mā te bhavatvantarāyo, sukhī dīghāyuko bhava' },
  blessPali3: { km: '♪ អាយុ វណ្ណោ សុខំ ពលំ', en: '♪ Āyu vaṇṇo sukhaṃ balaṃ' },
  blessSay: { km: 'សូមឱ្យញោមសុខសប្បាយ ធ្វើដំណើរដោយសុវត្ថិភាព', en: 'May you be well, and travel safely' },
  blessAgainSay: { km: 'ញោមបានទទួលពររួចហើយ សូមឱ្យសុខសប្បាយណា', en: 'You have your blessing already. Be well!' },
  // (by the empty dais: why there is nobody to bless him now; no E)
  blessMeal: { km: 'ព្រះសង្ឃកំពុងឆាន់ចង្ហាន់ថ្ងៃត្រង់ សូមមកវិញបន្តិចទៀត', en: 'The monk is at his noon meal: come back in a little while' },
  blessNight: { km: 'ពេលយប់ព្រះសង្ឃគង់សម្រាក សូមមកសុំពរនៅពេលថ្ងៃ', en: 'The monks rest at night: come for a blessing by day' },
  blessFest: { km: 'ថ្ងៃបុណ្យ ព្រះសង្ឃគង់ទទួលញាតិញោមនៅមុខវិហារ', en: 'On festival days the monks receive the faithful on the porch' },
  // (the calendar of events)
  blessCal: { km: 'ការប្រោះទឹកមន្ត និងចងអំបោះក្រហម', en: 'Blessings with the red string' },
  blessCalNote: { km: 'ព្រះសង្ឃមួយអង្គគង់ក្នុងវិហារ ប្រោះទឹកមន្ត និងចងអំបោះក្រហមឱ្យញាតិញោម (លើកលែងពេលឆាន់ថ្ងៃត្រង់)', en: 'A monk sits in the hall to sprinkle lustral water and tie the red string for visitors (not at his noon meal)' },
  blessCalBegins: { km: 'ព្រះសង្ឃគង់ប្រទានពរនៅក្នុងវិហារហើយ', en: 'A monk is giving blessings in the pagoda hall' },
  // Lotus from the boat, offered at a shrine (lotus…): roam/_lotus.ts
  lotusPick: { km: 'បេះផ្កាឈូក', en: 'Pick a lotus' },
  lotusPicked: { km: 'បានបេះផ្កាឈូកមួយទង ({n}/{max}) — យកទៅថ្វាយព្រះនៅទីសក្ការៈណាមួយ', en: 'You picked a lotus ({n}/{max}): offer it at a shrine' },
  lotusFull: { km: 'កាបូបពេញហើយ មិនអាចទុកផ្កាឈូកបានទៀតទេ', en: 'Your bag is full: no room for a lotus' },
  // (in his bag: its name, its button in "In my bag", a pick of it there)
  lotusName: { km: 'ក្រពុំផ្កាឈូក', en: 'Lotus bud' },
  lotusLabel: { km: 'ផ្កាឈូកសម្រាប់ថ្វាយព្រះ', en: 'Lotus to offer' },
  lotusHint: { km: 'យកផ្កាឈូកទៅថ្វាយនៅទីសក្ការៈណាមួយ ពេលអ្នកថ្វាយបង្គំ', en: 'Offer it at any shrine when you pray' },
  lotusKept: { km: '{name} នៅក្នុងកាបូបហើយ', en: '{name} is in your bag' },
  // (at a shrine with a lotus in his bag: he lays it down first, then prays)
  lotusOffer: { km: 'ថ្វាយផ្កាឈូក ហើយថ្វាយបង្គំ', en: 'Offer a lotus and pray' },
  lotusOffered: { km: 'បានថ្វាយផ្កាឈូកនៅ{place}', en: 'You offered a lotus at {place}' },
  lotusAtPagoda: { km: 'វត្តភូមិបណ្ដែតទឹក', en: 'the floating village pagoda' },
  lotusAtForest: { km: 'ព្រះពុទ្ធរូបក្នុងព្រៃ', en: 'the forest Buddha' },
  lotusAtLake: { km: 'ទីសក្ការៈមាត់បឹង', en: 'the shrine by the lake' },
  lotusAtKulen: { km: 'ទីសក្ការៈជើងភ្នំគូលែន', en: 'the shrine at the foot of Phnom Kulen' },
  lotusAtSpirit: { km: 'រានអ្នកតា', en: 'the spirit house' },
  lotusAtShrine: { km: 'ទីសក្ការៈ', en: 'the shrine' },
  // (the maps' badge on the bed in the lake: ui/_minimapSpots.ts)
  lotusMap: { km: 'វាលផ្កាឈូក', en: 'Lotus bed' },
  lotusTheMap: { km: 'វាលផ្កាឈូក', en: 'the lotus bed' },
  // Monkeys steal his snack (monkey…): roam/_monkeyThief.ts
  monkeyStole: { km: 'ស្វាឆក់យក{name}របស់អ្នកបាត់ហើយ!', en: 'A monkey stole your {name}!' },
  monkeySnack: { km: 'អាហារ', en: 'snack' },
  // Flying his own kite (kite…): roam/_kiteFly.ts
  kiteFly: { km: 'បង្ហោះខ្លែង', en: 'Fly your kite' },
  kiteReel: { km: 'ទាញខ្លែងចុះ', en: 'Reel it in' },
  kiteAsk: { km: 'សុំខ្លែងពីលោកតា', en: 'Ask for a kite' },
  kiteGive: { km: 'នេះ ចៅ! យកខ្លែងតូចនេះទៅហោះលេងចុះ', en: 'Here, child! Take this little kite and fly it!' },
  kiteGot: { km: 'បានខ្លែងមួយហើយ! ទៅបង្ហោះនៅវាលធំៗ ពេលមានខ្យល់', en: 'You have a kite! Fly it in an open field when the wind blows' },
  kiteBuy: { km: 'ទិញខ្លែង — {price}', en: 'Buy a kite — {price}' },
  kiteCardTitle: { km: 'ទិញខ្លែងមួយទេ?', en: 'Buy a kite?' },
  kiteCardNote: {
    km: 'ខ្លែងឯកតូចមួយ ធ្វើពីឫស្សី និងក្រដាស មានឯកបន្លឺសំឡេងពេលហោះ៖ {price}',
    en: 'A small khleng ek of bamboo and paper, with a bow that hums as it flies: {price}',
  },
  kiteCardGo: { km: 'ទិញ', en: 'Buy' },
  kiteCardStay: { km: 'ទេ អរគុណ', en: 'No, thanks' },
  kiteCalm: {
    km: 'ខ្យល់ខ្សោយពេក ខ្លែងហោះមិនឡើងទេ។ ខ្លែងហោះនៅរដូវប្រាំង ចាប់ពីបុណ្យអុំទូក ដល់ខែមីនា',
    en: 'The wind is too weak to fly a kite. Kites fly in the dry season, from the Water Festival to March',
  },
  kiteWet: { km: 'ភ្លៀង ឬព្រិលបែបនេះ ខ្លែងក្រដាសហោះមិនបានទេ ចាំមេឃស្រឡះសិន', en: "Not in this weather: a paper kite can't fly in rain or snow. Wait for a clear sky" },
  kiteRainIn: { km: 'ភ្លៀងមកហើយ! ទាញខ្លែងចុះសិន', en: 'Rain is coming! Bring the kite in' },
  kiteKeys: { km: 'ខ្លែង៖ W បណ្ដោយខ្សែ · S រមូរខ្សែ · A / D បត់ · Shift ដើរ · E ទាញខ្លែងចុះ', en: 'Kite: W let out line · S reel in · A / D steer · Shift walk with it · E bring it in' },
  kiteKeysTouch: {
    km: 'ខ្លែង៖ ដងបញ្ជារុញទៅមុខ បណ្ដោយខ្សែ · ទាញមកក្រោយ រមូរខ្សែ · ទៅឆ្វេង ឬស្ដាំ បត់ · រុញហួសរង្វង់ ដើរ',
    en: 'Kite: push the stick to let out line · pull back to reel in · left / right steers · past its ring: walk',
  },
  // (game pad: the left stick ↑ (pushed) ↓ (pulled back) ← →; {fast} R2 / RT: the pad's own names, glyphs.ts `padName`)
  kiteKeysPad: { km: 'ខ្លែង៖ ដងបញ្ជា ↑ បណ្ដោយខ្សែ · ↓ រមូរខ្សែ · ← → បត់ · {fast} ដើរ', en: 'Kite: stick ↑ let out line · ↓ reel in · ← → steer · {fast} walk with it' },
  kiteSnag: { km: 'ខ្លែងជាប់ដើមឈើហើយ! រមូរខ្សែយកវាមកវិញ', en: 'Your kite is caught in a tree! Reel it back in' },
  kiteDown: { km: 'ខ្លែងធ្លាក់ដល់ដីហើយ! រមូរខ្សែយកវាមកវិញ', en: 'Your kite came down! Reel it back in' },
  kiteTrees: { km: 'កុំដើរក្រោមដើមឈើ ឬដំបូល ខ្សែខ្លែងនឹងជាប់', en: 'Not under trees or roofs: the line would catch' },
  kiteMax: { km: 'ខ្សែអស់ហើយ!', en: "That's all the line!" },
  kiteHum: { km: 'ស្ដាប់! ឯកលើខ្លែងរបស់អ្នកកំពុងបន្លឺសំឡេង', en: 'Listen: the bow on your kite is humming' },
  // (the key help while he flies it, bottom left: the keys, or the pad's stick, R2 and □ / X)
  kiteKeyOut: { km: '↑ បណ្ដោយខ្សែ', en: '↑ let out line' },
  kiteKeyIn: { km: '↓ រមូរខ្សែ', en: '↓ reel in' },
  kiteKeySteer: { km: '← → បត់', en: '← → steer' },
  kiteKeyWalk: { km: 'ដើរទាំងបង្ហោះ', en: 'walk with it' },
  // (out of the kite season, once a visit, as he comes onto the families' kite field with his kite)
  kiteSeasonHint: { km: 'ខ្លែងហោះលើវាលនេះ នៅរដូវប្រាំង ពីបុណ្យអុំទូក ដល់ខែមីនា', en: 'Kites fly over this field in the dry season, from the Water Festival to March' },
  // Helping the farmers (farm…): roam/_farmWork.ts
  farmHelpPlant: { km: 'ជួយស្ទូងស្រូវ', en: 'Help plant rice' },
  farmHelpReap: { km: 'ជួយច្រូតស្រូវ', en: 'Help with the harvest' },
  // (in the row: E plants or cuts the next clump, {n} done of {max}; the stick walks him out of it)
  farmPlant: { km: 'ស្ទូង ({n}/{max})', en: 'Plant ({n}/{max})' },
  farmReap: { km: 'ច្រូត ({n}/{max})', en: 'Cut ({n}/{max})' },
  farmStop: { km: 'ដើរចេញ ដើម្បីឈប់', en: 'Walk away to stop' },
  // (the key help while he works, and the touch jump button: what E and Space do)
  farmKeyPlant: { km: 'ស្ទូង', en: 'plant' },
  farmKeyReap: { km: 'ច្រូត', en: 'cut' },
  farmBtnPlant: { km: 'ស្ទូង', en: 'Plant' },
  farmBtnReap: { km: 'ច្រូត', en: 'Cut' },
  farmCarry: { km: 'យកកណ្ដាប់ស្រូវទៅដាក់លើភ្លឺស្រែ', en: 'Taking the sheaf to the bund' },
  // (the farmer's bubble, and what she gives him: a num ansom for his bag, or riel when it is full)
  farmThanks: { km: 'អរគុណ!', en: 'Thank you!' },
  farmGift: { km: 'កសិករជូននំអន្សមមួយ ទុកក្នុងកាបូប ({n}/{max})', en: 'The farmer gives you a num ansom, kept in your bag ({n}/{max})' },
  farmPaid: { km: 'កាបូបពេញហើយ កសិករជូនលុយ {riel} ជំនួសវិញ', en: 'Your bag is full: the farmer gives you {riel} instead' },
  // (near the farmers out of season: when to come back; farmers/_sceneFarm.ts `farmModeOf`)
  farmComePlant: { km: 'រដូវស្ទូងស្រូវ ចាប់ផ្ដើមពេលភ្លៀងមក (ខែឧសភា–កក្កដា)', en: 'Planting starts with the rains (May–July)' },
  farmComeReap: { km: 'ស្រូវកំពុងលូតលាស់ មកជួយច្រូតនៅខែវិច្ឆិកា–មករា', en: 'The rice is growing: come back for the harvest (November–January)' },
  farmReapDone: { km: 'ច្រូតរួចហើយ មកជួយស្ទូងនៅខែឧសភា–កក្កដា', en: 'The harvest is in: come back for the planting (May–July)' },
  // The Water Festival boat race (race…): roam/_raceRow.ts
  raceJoin: { km: 'ចូលរួមអុំទូកង', en: 'Join a racing boat' },
  // (a toast the first time he comes near the landing by day: the way there)
  raceNear: { km: 'ទូកងនៅមាត់បឹងខាងជើង ខ្វះអ្នកអុំម្នាក់!', en: 'A racing boat on the north shore is one paddler short!' },
  // (at the gangway after dusk: a note with no key)
  raceNight: { km: 'ការប្រណាំងទូកងមានតែពេលថ្ងៃ · មកវិញពេលព្រឹក', en: 'The boat races are by day · come back in the morning' },
  raceReady: { km: 'ត្រៀម…', en: 'Ready…' },
  raceGo: { km: 'ទៅ!', en: 'Go!' },
  // (under the drum: the keys, then this)
  raceHint: { km: 'អុំពេលស្គរវាយ', en: 'Paddle as the drum strikes' },
  racePerfect: { km: 'ល្អឥតខ្ចោះ!', en: 'Perfect!' },
  raceGood: { km: 'ល្អ!', en: 'Good!' },
  raceEarly: { km: 'មុនពេក', en: 'Too early' },
  raceLate: { km: 'យឺតពេក', en: 'Too late' },
  raceMiss: { km: 'ភ្លាត់ចង្វាក់', en: 'Off the beat' },
  // (the caller, as the beat quickens: half way, then the last stretch)
  raceFaster: { km: 'លឿនឡើង!', en: 'Faster!' },
  racePush: { km: 'ប្រឹងឡើង!', en: 'Push!' },
  raceStreak: { km: 'ជាប់គ្នា', en: 'in a row' },
  raceUs: { km: 'ទូកយើង', en: 'Our boat' },
  raceThem: { km: 'ទូកគេ', en: 'Their boat' },
  raceMetres: { km: '{n} ម៉ែត្រ', en: '{n} m' },
  raceWin: { km: 'ឈ្នះ!', en: 'You won!' },
  raceWinBy: { km: 'ទូកយើងដល់មុន {n} ម៉ែត្រ', en: 'Our boat finished {n} m ahead' },
  raceLose: { km: 'ចាញ់ហើយ', en: 'Beaten' },
  raceLoseBy: { km: 'ទូកគេដល់មុន {n} ម៉ែត្រ — លើកក្រោយទៀត!', en: 'Their boat finished {n} m ahead: next time!' },
  raceTime: { km: '{s} វិនាទី', en: '{s} s' },
  raceStats: { km: 'ល្អឥតខ្ចោះ {p} · ល្អ {g} · ភ្លាត់ {m}', en: '{p} perfect · {g} good · {m} off' },
  racePrize: { km: 'រង្វាន់ {riel} និងកម្រងផ្កា', en: 'Prize: {riel} and a garland' },
  raceAgain: { km: 'ប្រណាំងម្ដងទៀត', en: 'Race again' },
  raceOut: { km: 'ឡើងគោក', en: 'Step ashore' },
  raceDusk: { km: 'ថ្ងៃលិចហើយ ទូកងចូលចតវិញ', en: 'The sun is down: the boats go in' },
  raceOver: { km: 'បុណ្យចប់ហើយ ទូកងចូលចតវិញ', en: 'The festival is over: the boats go in' },
  // (the calendar of events, calendar.ts)
  raceCalName: { km: 'ប្រណាំងទូកង', en: 'The boat races' },
  raceCalNote: { km: 'ទូកងប្រណាំងលើបឹងធំពេលថ្ងៃ — ចូលរួមអុំបាននៅមាត់បឹងខាងជើង', en: 'Racing boats on the great lake by day; join a crew on the north shore' },
  raceCalPlace: { km: 'បឹងធំ ក្បែរភូមិបណ្ដែតទឹក', en: 'The great lake, by the floating village' },
  raceCalBegins: { km: 'ការប្រណាំងទូកងចាប់ផ្ដើមហើយ!', en: 'The boat races have begun!' },
  // Kick the sey with the children (sey…): roam/_sey.ts
  seyJoin: { km: 'លេងសីជាមួយក្មេងៗ', en: 'Play sey with the children' },
  seyKick: { km: 'ទាត់', en: 'Kick' },
  seyLeave: { km: 'ឈប់លេង', en: 'Stop playing' },
  // (the key help while he plays: the stick walks him out of the game)
  seyAway: { km: 'ដើរចេញ', en: 'Walk away' },
  // (the counter while he plays: his kicks in a row, his best)
  seyStreak: { km: 'ទាត់ជាប់គ្នា', en: 'Kicks in a row' },
  seyBest: { km: 'កំណត់ត្រា {n}', en: 'Best {n}' },
  seyNewBest: { km: 'កំណត់ត្រាថ្មី! ទាត់ជាប់គ្នា {n} ដង', en: 'New best! {n} kicks in a row' },
  seyGone: { km: 'ក្មេងៗត្រឡប់ទៅផ្ទះវិញហើយ', en: 'The children have gone home' },
  // (the children's bubbles: they call him បង, big brother)
  seyCome: { km: 'មកលេងជាមួយគ្នា បង!', en: 'Come and play with us!' },
  seyNice: { km: 'ល្អណាស់!', en: 'Nice one!' },
  seyGood: { km: 'ពូកែមែន បង!', en: "You're good!" },
  seyAgain: { km: 'ម្ដងទៀត!', en: 'Again!' },
  seyOn: { km: 'កុំឱ្យធ្លាក់!', en: "Don't let it drop!" },
  seyWow: { km: 'អស្ចារ្យ! ទាត់កែងជើង!', en: 'Wow! A heel kick!' },
  seyOops: { km: 'ហាហា! ធ្លាក់ហើយ!', en: 'Ha ha! It fell!' },
  seyBye: { km: 'បាយបាយ បង!', en: 'Bye-bye!' },
  seyHome: { km: 'ល្ងាចហើយ ទៅផ្ទះសិន!', en: "It's getting late, we're going home!" },
  // The dog (dog…): roam/_dog*.ts
  dogPet: { km: 'អង្អែលឆ្កែ', en: 'Pet the dog' },
  dogPetName: { km: 'អង្អែល{name}', en: 'Pet {name}' },
  dogLikes: { km: 'ឆ្កែគ្រវីកន្ទុយ — វាចូលចិត្តអ្នកហើយ!', en: 'The dog wags its tail: it likes you!' },
  dogAdopt: { km: 'ឆ្កែចង់ទៅជាមួយអ្នក!', en: 'The dog wants to come with you!' },
  dogNameTitle: { km: 'ឈ្មោះឆ្កែរបស់អ្នក', en: "Your dog's name" },
  dogNameTitleNew: { km: 'ដាក់ឈ្មោះឱ្យឆ្កែរបស់អ្នក', en: 'Give your dog a name' },
  dogNameSub: { km: 'ឆ្កែស្រុកនេះនឹងដើរតាមអ្នកគ្រប់ទីកន្លែង', en: 'This village dog will go everywhere with you' },
  dogNameSave: { km: 'យកឈ្មោះនេះ', en: 'This name' },
  dogNameLater: { km: 'បិទ', en: 'Close' },
  dogNameKeep: { km: 'ទុកឈ្មោះ {name}', en: 'Keep {name}' },
  dogNamed: { km: 'ឆ្កែរបស់អ្នកឈ្មោះ {name}', en: 'Your dog is called {name}' },
  dogNameMenu: { km: 'ឈ្មោះឆ្កែ', en: "Dog's name" },
  dogFollows: { km: '{name} ដើរតាមអ្នកហើយ · ចុច {key} ហៅវាមក', en: '{name} follows you now · {key} calls it' },
  dogFollowsMenu: { km: '{name} ដើរតាមអ្នកហើយ · ហៅវាមកពីម៉ឺនុយ', en: '{name} follows you now · call it from the menu' },
  dogScratchHint: { km: 'នៅក្បែរ{name}៖ ចុច {key} អេះត្រចៀកវា', en: 'Beside {name}: {key} scratches its ears' },
  dogCall: { km: 'ហៅឆ្កែ', en: 'Call the dog' },
  dogComing: { km: '{name} កំពុងរត់មករកអ្នក!', en: '{name} is coming!' },
  dogHere: { km: '{name} នៅក្បែរអ្នកហើយ', en: '{name} is right here' },
  dogFar: { km: '{name} នៅឆ្ងាយ · ចុច {key} ហៅវាមក', en: '{name} is far away · {key} calls it' },
  dogFarMenu: { km: '{name} នៅឆ្ងាយ · ហៅវាមកពីម៉ឺនុយ', en: '{name} is far away · call it from the menu' },
  dogNoWay: { km: '{name} មិនអាចមកដល់ទីនេះបានទេ · វានៅរង់ចាំអ្នក', en: "{name} can't get up here · it waits for you" },
  dogDoor: { km: 'ឆ្កែមិនចូលទីសក្ការៈទេ · {name} រង់ចាំអ្នកនៅខាងក្រៅ', en: "Dogs stay out of holy halls · {name} waits for you outside" },
  dogNone: { km: 'អ្នកមិនទាន់មានឆ្កែទេ — មានឆ្កែស្រុកមួយក្បាលដេកក្បែរហាងលក់ទំនិញ នៅភូមិត្នោត', en: 'No dog yet: a friendly village dog naps by the little shop in the sugar-palm village' },
  // His stilt house (home…): roam/_home*.ts
  homeMap: { km: 'ផ្ទះខ្ញុំ', en: 'My home' },
  homeTheMap: { km: 'ផ្ទះខ្ញុំ', en: 'home' },
  // (the grandmother who keeps the key: people/_sceneHome.ts; she calls him ចៅ, grandchild)
  homeTalk: { km: 'និយាយជាមួយយាយ', en: 'Talk to Grandma' },
  homeCall: { km: 'ចៅ! មកនេះបន្តិចមក!', en: 'Grandchild! Come here a moment!' },
  homeEmpty: { km: 'ផ្ទះនេះនៅទំនេរយូរហើយ គ្មាននរណានៅទេ', en: 'This house has stood empty a long time' },
  homeYours: { km: 'ផ្ទះនេះជារបស់ចៅហើយ។ ស្នាក់នៅប៉ុន្មានក៏បាន', en: 'This house is yours now. Stay as long as you like' },
  homeGoIn: { km: 'ទៅ ចូលមើលផ្ទះទៅចៅ!', en: 'Go on, have a look inside!' },
  homeGot: { km: 'បានកូនសោហើយ! ផ្ទះឈើក្បែរភ្នំគូលែននេះ ជាផ្ទះរបស់អ្នក', en: 'You have the key! The stilt house below Phnom Kulen is your home' },
  homeLocked: { km: 'ទ្វារចាក់សោ — យាយនៅក្បែរនេះកាន់កូនសោ', en: 'Locked — the grandmother nearby has the key' },
  homeOpen: { km: 'បើកទ្វារ', en: 'Open the door' },
  homeSleep: { km: 'ដេកសម្រាក', en: 'Sleep' },
  // (the card: how long he sleeps, roam/_homeCard.ts)
  homeAsk: { km: 'ដេកដល់ពេលណា?', en: 'Sleep until…' },
  homeNow: { km: 'ឥឡូវ៖ {when}', en: 'Now: {when}' },
  homeTilDawn: { km: 'ដល់ព្រលឹម', en: 'Until dawn' },
  homeTilAfternoon: { km: 'ដល់ពេលរសៀល', en: 'Until the afternoon' },
  homeTilEvent: { km: 'ភ្ញាក់ទាន់{event}', en: 'Wake for: {event}' },
  homeRest: { km: 'សម្រាកបន្តិច', en: 'Rest a while' },
  homeHeld: { km: 'ពេលវេលាកំពុងឈប់ ដូច្នេះសម្រាកបានតែបន្តិច។ ដើម្បីដេកដល់ព្រឹក៖ {path}', en: 'Time stands still, so only a short rest. To sleep till morning: {path}' },
  homeCancel: { km: 'ទេ ចាំសិន', en: 'Not now' },
  // (waking up)
  homeMorning: { km: 'អរុណសួស្ដី! ព្រះអាទិត្យរះហើយ', en: 'Good morning! The sun is up' },
  homeAfternoon: { km: 'ទិវាសួស្ដី! ដេកបានស្រួលណាស់', en: 'Good afternoon! What a good sleep' },
  homeWoke: { km: 'ភ្ញាក់ទាន់ពេល៖ {event}', en: 'Up in time: {event}' },
  homeRested: { km: 'បានសម្រាកហើយ ស្រស់ស្រាយណាស់', en: 'Rested: you feel fresh again' },
  // His name in Khmer letters (name…): roam/_name*.ts, khmerName.ts
  nameTitle: { km: 'ឈ្មោះរបស់ខ្ញុំ', en: 'My name' },
  nameSub: { km: 'វាយឈ្មោះរបស់អ្នក ហើយមើលវាជាអក្សរខ្មែរ', en: 'Type your name and see it in Khmer letters' },
  nameSubPass: { km: 'សរសេរឈ្មោះរបស់អ្នកលើលិខិតឆ្លងដែនប្រាសាទ', en: 'Put your name in your temple passport' },
  nameType: { km: 'វាយឈ្មោះ ជាអក្សរឡាតាំង ឬខ្មែរ', en: 'Type a name, in Latin or Khmer letters' },
  nameField: { km: 'ឈ្មោះ', en: 'Name' },
  nameEmpty: { km: 'ឈ្មោះ', en: 'Your name' },
  nameOther: { km: 'ឬសរសេរបែបនេះ', en: 'Or written' },
  namePick: { km: 'ឬជ្រើសឈ្មោះខ្មែរ', en: 'Or pick a Khmer name' },
  nameSave: { km: 'រក្សាទុក', en: 'Save' },
  nameLater: { km: 'ពេលក្រោយ', en: 'Not now' },
  nameClear: { km: 'លុបឈ្មោះ', en: 'Remove my name' },
  nameClose: { km: 'បិទ', en: 'Close' },
  nameBack: { km: 'លុបមួយតួ', en: 'Delete a letter' },
  nameSpace: { km: 'ដកឃ្លា', en: 'Space' },
  nameSaved: { km: 'ឈ្មោះរបស់អ្នក៖ {name}', en: 'Your name: {name}' },
  nameCleared: { km: 'បានលុបឈ្មោះហើយ', en: 'Name removed' },
  nameMenu: { km: 'ឈ្មោះខ្ញុំ', en: 'My name' },
  nameHolder: { km: 'ឈ្មោះម្ចាស់', en: 'Holder' },
  nameWrite: { km: 'សរសេរឈ្មោះរបស់អ្នក', en: 'Write your name' },
  nameEdit: { km: 'កែ', en: 'Edit' },
  namePhotoBy: { km: 'ថតដោយ {name}', en: 'Photo by {name}' },
  // (people who greet him back, now and then by his name: people/_greetBack.ts)
  nameHi: { km: 'សួស្ដី {name}!', en: 'Hi, {name}!' },
  nameKid: { km: 'សួស្ដីបង{name}!', en: 'Hi, {name}!' },
  nameElder: { km: 'សុខសប្បាយទេ ចៅ{name}?', en: 'Are you well, {name}?' },
  nameSeller: { km: 'អញ្ជើញបង{name}!', en: 'Come in, {name}!' },
  // The umbrella (umb…): roam/_umbrella.ts
  umbName: { km: 'ឆ័ត្រ', en: 'Umbrella' },
  umbUp: { km: 'បើកឆ័ត្រ', en: 'Umbrella up' },
  umbDown: { km: 'បិទឆ័ត្រ', en: 'Umbrella down' },
  // (the first time it opens by itself in a visit; with a keyboard, `umbHint` after it)
  umbRain: { km: 'ភ្លៀងហើយ! បើកឆ័ត្រ', en: "It's raining: umbrella up" },
  umbSnow: { km: 'ព្រិលធ្លាក់ហើយ! បើកឆ័ត្រ', en: "It's snowing: umbrella up" },
  umbHint: { km: 'ចុច {key} ដើម្បីបិទ', en: '{key} closes it' },
  // (8 while a ride or another add-on has him: as the binoculars say it)
  umbHandsBusy: { km: 'ដៃគាត់កំពុងរវល់', en: 'His hands are busy' },
  // The binoculars (bino…): roam/_binoculars.ts
  binoName: { km: 'កែវយឹត', en: 'Binoculars' },
  // (the touch layout's ✕ while they are up; the key hint's "pinch to zoom" on touch)
  binoClose: { km: 'ទុកកែវយឹតវិញ', en: 'Put the binoculars away' },
  binoPinch: { km: 'ច្បិចដើម្បីពង្រីក', en: 'pinch to zoom' },
  // (why not now)
  binoHandsBusy: { km: 'ដៃគាត់កំពុងរវល់', en: 'His hands are busy' },
  binoNoHang: { km: 'ពេលជិះខ្លែងហោះ ដៃត្រូវតែកាន់របារ', en: 'On the hang glider his hands stay on the bar' },
  binoNoChute: { km: 'ពេលលោតឆ័ត្រយោង ដៃត្រូវតែកាន់ខ្សែ', en: 'Under the parachute his hands stay on the lines' },
  binoFishing: { km: 'ឈប់ស្ទូចសិន ទើបអាចមើលកែវយឹតបាន', en: 'Stop fishing first to use the binoculars' },
  // (a nature book page filled through them, not with a photo: roam/_bookUi.ts)
  binoSeen: { km: 'បានឃើញតាមកែវយឹត', en: 'Seen through the binoculars' },
  // Smiles for his camera (smile…): smile.ts, people/_smileBack.ts
  // Selling his fish (sell…): roam/_fishSell.ts
  // (the catch card: what a fish seller would pay, keep it in his fish basket or let it go)
  sellWorth: { km: 'លក់បានប្រហែល {price}', en: 'Sells for about {price}' },
  sellKeep: { km: 'ទុកក្នុងកន្ត្រក', en: 'Keep it' },
  sellLetGo: { km: 'ដោះលែង', en: 'Let it go' },
  sellBasket: { km: 'កន្ត្រកត្រី', en: 'Fish basket' },
  sellFull: { km: 'កន្ត្រកពេញហើយ', en: 'The basket is full' },
  sellFullNote: { km: 'កន្ត្រកពេញហើយ — យកត្រីទៅលក់សិន ទើបទុកបានទៀត', en: 'Your basket is full: sell your fish, then you can keep more' },
  sellNoKeep: { km: 'ត្រីមិនអាចទុកបានយូរទេ — លក់វានៅថ្ងៃនេះ', en: 'Fish do not keep: sell them today' },
  sellKept: { km: 'ដាក់ក្នុងកន្ត្រកហើយ ({n}/{max})', en: 'Into the basket ({n}/{max})' },
  sellWhere: { km: 'យកទៅលក់ឲ្យអ្នកលក់ត្រីនៅផ្សារ', en: 'Sell them to a fish seller at a market' },
  sellCm: { km: '{cm} ស.ម.', en: '{cm} cm' },
  // (at a fish seller: the prompt; who buys; away at night, or the grill until midday)
  sellPrompt: { km: 'លក់ត្រី ({n})', en: 'Sell your fish ({n})' },
  sellAway: { km: '{name} មិននៅទេ · មកវិញពេលព្រឹក', en: '{name}: not here now · come back in the morning' },
  sellAwayNoon: { km: '{name} មិននៅទេ · មកវិញពេលថ្ងៃត្រង់', en: '{name}: not here now · come back at midday' },
  sellFishSeller: { km: 'អ្នកលក់ត្រី', en: 'Fish seller' },
  sellFishStall: { km: 'តូបលក់ត្រី', en: 'Fish stall' },
  sellFishBoat: { km: 'ទូកលក់ត្រី', en: 'Fish boat' },
  sellGrill: { km: 'អ្នកលក់ត្រីអាំង', en: 'Grilled fish seller' },
  // (the sale card: her words while she weighs them, then; selling all or one; the money in his purse)
  sellWeigh: { km: 'ចាំខ្ញុំថ្លឹងមើលសិន…', en: 'Let me weigh them…' },
  sellOffer: { km: 'ត្រីស្រស់ល្អណាស់ បង!', en: 'Nice fresh fish!' },
  sellAgain: { km: 'អរគុណបង! មានត្រីទៀត យកមកលក់ទៀតណា៎', en: 'Thank you! Bring me more fish' },
  sellAll: { km: 'លក់ទាំងអស់', en: 'Sell all' },
  sellSoldAll: { km: 'លក់អស់ហើយ', en: 'All sold' },
  sellOne: { km: 'លក់ {name}', en: 'Sell: {name}' },
  sellEarned: { km: 'បានលុយ {n}', en: 'Earned {n}' },
  // Clothes from the market (wear…): roam/_wardrobe*.ts
  // (E at the morning market's krama stall; closed: no E)
  wearBuy: { km: 'ទិញខោអាវ', en: 'Buy clothes' },
  wearClosed: { km: 'តូបក្រមាបិទហើយ · បើកវិញពេលព្រឹក', en: 'The krama stall is closed · it opens in the morning' },
  // (the card: the stall's name and the seller's words; his wardrobe, the explorer menu's entry)
  wearStall: { km: 'តូបលក់ក្រមា និងខោអាវ', en: 'Krama and clothes stall' },
  wearAsk: { km: 'ក្រមាល្អៗ ខោអាវស្អាតៗ! យកមួយណាដែរ បង?', en: 'Fine kramas, nice clothes! Which one would you like?' },
  wearSuits: { km: 'ពាក់ទៅស្អាតណាស់ បង!', en: 'Looks great on you!' },
  wearTitle: { km: 'ខោអាវរបស់ខ្ញុំ', en: 'My clothes' },
  wearPick: { km: 'ជ្រើសរើសមួយ ដើម្បីពាក់ ឬដោះចេញ', en: 'Pick one to put it on or take it off' },
  wearKramas: { km: 'ក្រមា', en: 'Kramas' },
  wearShirts: { km: 'អាវ', en: 'Shirts' },
  wearTrousers: { km: 'ខោ', en: 'Trousers' },
  wearHats: { km: 'មួក', en: 'Hats' },
  // (a row: what he owns, what he wears; a look that hides it)
  wearYours: { km: 'បានទិញហើយ', en: 'Yours' },
  wearPutOn: { km: 'ពាក់', en: 'Wear' },
  wearOnNow: { km: 'កំពុងពាក់', en: 'Wearing' },
  wearTakeOff: { km: 'ដោះចេញ', en: 'Take off' },
  wearHidden: { km: 'រូបរាងនេះមិនបង្ហាញទេ (G)', en: 'Not shown in this look (G)' },
  wearOriginal: { km: 'រូបរាងដើម', en: 'Original look' },
  wearNone: { km: 'មិនទាន់មានទេ — ទិញបាននៅតូបក្រមា ផ្សារព្រឹក ភូមិត្នោត', en: 'None yet — buy them at the krama stall of the morning market, Sugar Palm Village' },
  wearCount: { km: 'មាន {n}/{max}', en: '{n} of {max}' },
  // (toasts)
  wearNowWearing: { km: 'កំពុងពាក់៖ {name}', en: 'Now wearing: {name}' },
  wearTookOff: { km: 'បានដោះ៖ {name}', en: 'Took off: {name}' },
  wearBackOriginal: { km: 'ត្រឡប់មករូបរាងដើមវិញ', en: 'Back to the original look' },
  // Pchum Ben (pchum…): festival/_pchumBen.ts
  pchumName: { km: 'បុណ្យភ្ជុំបិណ្ឌ', en: 'Pchum Ben' },
  pchumNote: { km: 'បោះបាយបិណ្ឌមុនភ្លឺ · យកចង្ហាន់ទៅប្រគេនព្រះសង្ឃ · ឧទ្ទិសកុសលដល់ដូនតា', en: 'Rice balls before dawn · food for the monks · merit for the ancestors' },
  pchumPlace: { km: 'វត្តក្នុងភូមិ', en: 'The village pagoda' },
  pchumBegins: { km: 'បុណ្យភ្ជុំបិណ្ឌចាប់ផ្ដើមហើយ', en: 'Pchum Ben has begun' },
  // (E near the walk round the hall before dawn; then E or Space throws one, n left)
  pchumJoin: { km: 'បោះបាយបិណ្ឌ', en: 'Throw bay ben' },
  pchumThrow: { km: 'បោះបាយបិណ្ឌ (នៅសល់ {n})', en: 'Throw a rice ball ({n} left)' },
  // (who hands him the rice balls: the grandmother by the stair, or someone in the line)
  pchumGiveGrandma: { km: 'យាយ៖ «នេះ ចៅ! ដើរជុំវិហារជាមួយគេ ហើយបោះបាយបិណ្ឌឧទ្ទិសដល់ដូនតា»', en: 'Grandma: "Here, child! Walk round the hall with us and throw them for the ancestors"' },
  pchumGive: { km: 'គេហុចបាយបិណ្ឌមកឱ្យ៖ ដើរជុំវិហារ ហើយបោះឧទ្ទិសដល់ដូនតា', en: 'Someone hands you rice balls: walk round the hall and throw them for the ancestors' },
  pchumHow: { km: 'E ឬ Space បោះបាយបិណ្ឌ · ទាញដងបញ្ជាចេញ ដើម្បីចេញពីជួរ', en: 'E or Space throws a rice ball · push the stick away to step out' },
  pchumThanks: { km: 'សាធុ! សូមឱ្យដូនតាទទួលបានកុសលនេះ', en: 'Sathu! May the ancestors receive this merit' },
  // Visak Bochea (visak…): festival/_visak.ts
  visakName: { km: 'បុណ្យវិសាខបូជា', en: 'Visak Bochea' },
  visakNote: { km: 'ដង្ហែទៀនដើរប្រទក្សិណជុំវិហារ នៅយប់ពេញបូណ៌មី', en: 'A candle procession round the hall under the full moon' },
  visakPlace: { km: 'វត្តក្នុងភូមិ', en: 'The village pagoda' },
  visakBegins: { km: 'ថ្ងៃនេះបុណ្យវិសាខបូជា', en: 'Today is Visak Bochea' },
  // (E near the procession; while in it: the rounds, stepping out)
  visakJoin: { km: 'ចូលដង្ហែប្រទក្សិណ', en: 'Join the procession' },
  visakGiveGrandma: { km: 'យាយ៖ «យកទៀន ធូប និងផ្កាឈូកនេះទៅ ចៅ ដើរប្រទក្សិណបីជុំ»', en: 'Grandma: "Take this candle, incense and lotus, child, and walk round three times"' },
  visakGive: { km: 'គេហុចទៀន ធូប និងផ្កាឈូកមកឱ្យ៖ ដើរប្រទក្សិណបីជុំ', en: 'Someone hands you a candle, incense and a lotus: walk round three times' },
  visakRound: { km: 'ជុំទី {n} / ៣', en: 'Round {n} of 3' },
  visakOut: { km: 'ចេញពីជួរ', en: 'Step out of the line' },
  visakPlaceIt: { km: 'គ្រប់បីជុំហើយ! ទៅថ្វាយទៀន និងផ្កាឈូកនៅមុខព្រះវិហារ', en: 'Three rounds! Now place your candle and lotus before the hall' },
  visakThanks: { km: 'សាធុ! សូមឱ្យមានសេចក្ដីសុខ', en: 'Sathu! May you be at peace' },
  // The equinox sunrise over Angkor Wat (equi…): sky/_equinox.ts
  equiName: { km: 'ព្រះអាទិត្យរះចំកំពូលអង្គរវត្ត', en: 'The equinox sunrise' },
  equiNote: {
    km: 'ពីរដងក្នុងមួយឆ្នាំ នៅជុំវិញថ្ងៃទី២០ មីនា និងថ្ងៃទី២២ កញ្ញា ព្រះអាទិត្យរះចំពីក្រោយកំពូលកណ្ដាលនៃប្រាសាទអង្គរវត្ត។ មនុស្សម្នាមកជួបជុំគ្នាតាំងពីព្រលឹម ដើម្បីទស្សនា។',
    en: "Twice a year, around 20 March and 22 September, the sun rises right behind Angkor Wat's central tower. People gather before dawn to watch it.",
  },
  equiPlace: { km: 'អង្គរវត្ត · ផ្លូវដើរមុខប្រាសាទ', en: 'Angkor Wat · the causeway before the temple' },
  equiBegins: { km: 'មនុស្សម្នាកំពុងមកជួបជុំនៅមុខអង្គរវត្ត ដើម្បីមើលព្រះអាទិត្យរះចំកំពូល', en: 'People are gathering before Angkor Wat to watch the sun rise over its central tower' },
  equiEve: { km: 'ព្រឹកស្អែក ព្រះអាទិត្យនឹងរះចំកំពូលកណ្ដាលអង្គរវត្ត — មើលពីផ្លូវដើរមុខប្រាសាទ រវាងស្រះទាំងពីរ', en: "Tomorrow at dawn the sun rises over Angkor Wat's central tower — watch from the causeway between the reflecting pools" },
  equiSoon: { km: 'ព្រឹកនេះ ព្រះអាទិត្យនឹងរះចំកំពូលកណ្ដាលអង្គរវត្ត — មើលពីផ្លូវដើរមុខប្រាសាទ រវាងស្រះទាំងពីរ', en: "This dawn the sun rises over Angkor Wat's central tower — watch from the causeway between the reflecting pools" },
  equiNow: { km: 'ព្រះអាទិត្យកំពុងរះចំកំពូលកណ្ដាលអង្គរវត្ត!', en: "The sun is rising right over Angkor Wat's central tower!" },
  equiNowHere: { km: 'ព្រះអាទិត្យកំពុងរះចំកំពូលកណ្ដាល! លើកកាមេរ៉ាថតទុកជាអនុស្សាវរីយ៍', en: 'The sun is rising right over the central tower! Raise your camera for a keepsake' },
  // (the passport's section for rare moments, roam/_bookUi.ts; its stamp's own name is in roam/_bookData.ts)
  equiMoments: { km: 'ពេលវេលាដ៏កម្រ', en: 'Rare moments' },
} satisfies Record<string, Record<Lang, string>>;
export type WordKey = keyof typeof WORDS;

let current: Lang = 'km';
const listeners: ((l: Lang) => void)[] = [];

export const lang = (): Lang => current;

/** Change the language: the page's `lang` (for the Khmer styles in map.css), then everyone showing words. */
export function setLang(l: Lang): void {
  document.documentElement.lang = l;
  if (l === current) return;
  current = l;
  for (const fn of listeners) fn(l);
}

export function onLang(fn: (l: Lang) => void): void {
  listeners.push(fn);
}

export function t(key: WordKey, vars: Record<string, string> = {}): string {
  return WORDS[key][current].replace(/\{(\w+)\}/g, (_, k: string) => vars[k] ?? '');
}

export const placeText = (p: PlaceDef): PlaceText => (current === 'km' ? p.km : p);

const KHMER_DIGITS = '០១២៣៤៥៦៧៨៩';
export const num = (s: string | number): string => (current === 'km' ? String(s).replace(/[0-9]/g, (d) => KHMER_DIGITS[+d]) : String(s));
